/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SalesReturn } from '../../models/sales-return';
import { SalesReturnRequest } from '../../models/sales-return-request';

export interface SalesReturnsCreate$Json$Params {
      body: SalesReturnRequest
}

export function salesReturnsCreate$Json(http: HttpClient, rootUrl: string, params: SalesReturnsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
  const rb = new RequestBuilder(rootUrl, salesReturnsCreate$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SalesReturn>;
    })
  );
}

salesReturnsCreate$Json.PATH = '/api/sales/returns/';
