/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Invoice } from '../../models/invoice';
import { PatchedInvoiceRequest } from '../../models/patched-invoice-request';

export interface SalesInvoicesPartialUpdate$Json$Params {

/**
 * A unique integer value identifying this invoice.
 */
  id: number;
      body?: PatchedInvoiceRequest
}

export function salesInvoicesPartialUpdate$Json(http: HttpClient, rootUrl: string, params: SalesInvoicesPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
  const rb = new RequestBuilder(rootUrl, salesInvoicesPartialUpdate$Json.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Invoice>;
    })
  );
}

salesInvoicesPartialUpdate$Json.PATH = '/api/sales/invoices/{id}/';
