/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerPayment } from '../../models/customer-payment';
import { ReasonRequest } from '../../models/reason-request';

export interface SalesPaymentsVoidCreate$XWwwFormUrlencoded$Params {

/**
 * A unique integer value identifying this customer payment.
 */
  id: number;
      body: ReasonRequest
}

export function salesPaymentsVoidCreate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: SalesPaymentsVoidCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
  const rb = new RequestBuilder(rootUrl, salesPaymentsVoidCreate$XWwwFormUrlencoded.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerPayment>;
    })
  );
}

salesPaymentsVoidCreate$XWwwFormUrlencoded.PATH = '/api/sales/payments/{id}/void/';
