/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedSalesReturnRequest } from '../../models/patched-sales-return-request';
import { SalesReturn } from '../../models/sales-return';

export interface SalesReturnsPartialUpdate$Json$Params {

/**
 * A unique integer value identifying this sales return.
 */
  id: number;
      body?: PatchedSalesReturnRequest
}

export function salesReturnsPartialUpdate$Json(http: HttpClient, rootUrl: string, params: SalesReturnsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
  const rb = new RequestBuilder(rootUrl, salesReturnsPartialUpdate$Json.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SalesReturn>;
    })
  );
}

salesReturnsPartialUpdate$Json.PATH = '/api/sales/returns/{id}/';
