/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoteRequest } from '../../models/note-request';
import { Quotation } from '../../models/quotation';

export interface SalesQuotationsRejectCreate$FormData$Params {

/**
 * A unique integer value identifying this quotation.
 */
  id: number;
      body: NoteRequest
}

export function salesQuotationsRejectCreate$FormData(http: HttpClient, rootUrl: string, params: SalesQuotationsRejectCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
  const rb = new RequestBuilder(rootUrl, salesQuotationsRejectCreate$FormData.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Quotation>;
    })
  );
}

salesQuotationsRejectCreate$FormData.PATH = '/api/sales/quotations/{id}/reject/';
