/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SalesReturn } from '../../models/sales-return';

export interface SalesReturnsPostCreate$Params {

/**
 * A unique integer value identifying this sales return.
 */
  id: number;
}

export function salesReturnsPostCreate(http: HttpClient, rootUrl: string, params: SalesReturnsPostCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
  const rb = new RequestBuilder(rootUrl, salesReturnsPostCreate.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SalesReturn>;
    })
  );
}

salesReturnsPostCreate.PATH = '/api/sales/returns/{id}/post/';
