/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerPayment } from '../../models/customer-payment';

export interface SalesPaymentsRetrieve$Params {

/**
 * A unique integer value identifying this customer payment.
 */
  id: number;
}

export function salesPaymentsRetrieve(http: HttpClient, rootUrl: string, params: SalesPaymentsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
  const rb = new RequestBuilder(rootUrl, salesPaymentsRetrieve.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerPayment>;
    })
  );
}

salesPaymentsRetrieve.PATH = '/api/sales/payments/{id}/';
