/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InitialPassword } from '../../models/initial-password';

export interface UsersResetPasswordCreate$Params {

/**
 * A unique integer value identifying this user.
 */
  id: number;
}

export function usersResetPasswordCreate(http: HttpClient, rootUrl: string, params: UsersResetPasswordCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<InitialPassword>> {
  const rb = new RequestBuilder(rootUrl, usersResetPasswordCreate.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InitialPassword>;
    })
  );
}

usersResetPasswordCreate.PATH = '/api/users/{id}/reset-password/';
