/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedUserRequest } from '../../models/patched-user-request';
import { User } from '../../models/user';

export interface UsersPartialUpdate$XWwwFormUrlencoded$Params {

/**
 * A unique integer value identifying this user.
 */
  id: number;
      body?: PatchedUserRequest
}

export function usersPartialUpdate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: UsersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
  const rb = new RequestBuilder(rootUrl, usersPartialUpdate$XWwwFormUrlencoded.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<User>;
    })
  );
}

usersPartialUpdate$XWwwFormUrlencoded.PATH = '/api/users/{id}/';
