/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserCreated } from '../../models/user-created';
import { UserCreateRequest } from '../../models/user-create-request';

export interface UsersCreate$FormData$Params {
      body: UserCreateRequest
}

export function usersCreate$FormData(http: HttpClient, rootUrl: string, params: UsersCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<UserCreated>> {
  const rb = new RequestBuilder(rootUrl, usersCreate$FormData.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserCreated>;
    })
  );
}

usersCreate$FormData.PATH = '/api/users/';
