/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedWarrantyClaimRequest } from '../../models/patched-warranty-claim-request';
import { WarrantyClaim } from '../../models/warranty-claim';

export interface WarrantyClaimsPartialUpdate$Json$Params {

/**
 * A unique integer value identifying this warranty claim.
 */
  id: number;
      body?: PatchedWarrantyClaimRequest
}

export function warrantyClaimsPartialUpdate$Json(http: HttpClient, rootUrl: string, params: WarrantyClaimsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<WarrantyClaim>> {
  const rb = new RequestBuilder(rootUrl, warrantyClaimsPartialUpdate$Json.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WarrantyClaim>;
    })
  );
}

warrantyClaimsPartialUpdate$Json.PATH = '/api/warranty/claims/{id}/';
