/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductSupplier } from '../../models/product-supplier';
import { ProductSupplierRequest } from '../../models/product-supplier-request';

export interface PartnersProductSuppliersCreate$FormData$Params {
      body: ProductSupplierRequest
}

export function partnersProductSuppliersCreate$FormData(http: HttpClient, rootUrl: string, params: PartnersProductSuppliersCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
  const rb = new RequestBuilder(rootUrl, partnersProductSuppliersCreate$FormData.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductSupplier>;
    })
  );
}

partnersProductSuppliersCreate$FormData.PATH = '/api/partners/product-suppliers/';
