/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedSupplierRequest } from '../../models/patched-supplier-request';
import { Supplier } from '../../models/supplier';

export interface PartnersSuppliersPartialUpdate$FormData$Params {

/**
 * A unique integer value identifying this supplier.
 */
  id: number;
      body?: PatchedSupplierRequest
}

export function partnersSuppliersPartialUpdate$FormData(http: HttpClient, rootUrl: string, params: PartnersSuppliersPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
  const rb = new RequestBuilder(rootUrl, partnersSuppliersPartialUpdate$FormData.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Supplier>;
    })
  );
}

partnersSuppliersPartialUpdate$FormData.PATH = '/api/partners/suppliers/{id}/';
