/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Customer } from '../../models/customer';
import { CustomerRequest } from '../../models/customer-request';

export interface PartnersCustomersCreate$XWwwFormUrlencoded$Params {
      body: CustomerRequest
}

export function partnersCustomersCreate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: PartnersCustomersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Customer>> {
  const rb = new RequestBuilder(rootUrl, partnersCustomersCreate$XWwwFormUrlencoded.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Customer>;
    })
  );
}

partnersCustomersCreate$XWwwFormUrlencoded.PATH = '/api/partners/customers/';
