/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerLookup } from '../../models/customer-lookup';

export interface PartnersCustomersLookupList$Params {

/**
 * true: active only; false: inactive only.
 */
  active?: 'false' | 'true';

/**
 * yes: allowed credit (on hold included); no: cash only; hold: on credit hold.
 */
  credit?: 'hold' | 'no' | 'yes';

/**
 * Price tier.
 */
  price_tier?: 'RETAIL' | 'WHOLESALE';

/**
 * Matches codes, names and numbers.
 */
  search?: string;
}

export function partnersCustomersLookupList(http: HttpClient, rootUrl: string, params?: PartnersCustomersLookupList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerLookup>>> {
  const rb = new RequestBuilder(rootUrl, partnersCustomersLookupList.PATH, 'get');
  if (params) {
    rb.query('active', params.active, {});
    rb.query('credit', params.credit, {});
    rb.query('price_tier', params.price_tier, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CustomerLookup>>;
    })
  );
}

partnersCustomersLookupList.PATH = '/api/partners/customers/lookup/';
