/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Supplier } from '../../models/supplier';
import { SupplierRequest } from '../../models/supplier-request';

export interface PartnersSuppliersCreate$XWwwFormUrlencoded$Params {
      body: SupplierRequest
}

export function partnersSuppliersCreate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: PartnersSuppliersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
  const rb = new RequestBuilder(rootUrl, partnersSuppliersCreate$XWwwFormUrlencoded.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Supplier>;
    })
  );
}

partnersSuppliersCreate$XWwwFormUrlencoded.PATH = '/api/partners/suppliers/';
