/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductSupplier } from '../../models/product-supplier';

export interface PartnersProductSuppliersRetrieve$Params {

/**
 * A unique integer value identifying this product supplier.
 */
  id: number;
}

export function partnersProductSuppliersRetrieve(http: HttpClient, rootUrl: string, params: PartnersProductSuppliersRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
  const rb = new RequestBuilder(rootUrl, partnersProductSuppliersRetrieve.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductSupplier>;
    })
  );
}

partnersProductSuppliersRetrieve.PATH = '/api/partners/product-suppliers/{id}/';
