/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedProductSupplierRequest } from '../../models/patched-product-supplier-request';
import { ProductSupplier } from '../../models/product-supplier';

export interface PartnersProductSuppliersPartialUpdate$FormData$Params {

/**
 * A unique integer value identifying this product supplier.
 */
  id: number;
      body?: PatchedProductSupplierRequest
}

export function partnersProductSuppliersPartialUpdate$FormData(http: HttpClient, rootUrl: string, params: PartnersProductSuppliersPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
  const rb = new RequestBuilder(rootUrl, partnersProductSuppliersPartialUpdate$FormData.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductSupplier>;
    })
  );
}

partnersProductSuppliersPartialUpdate$FormData.PATH = '/api/partners/product-suppliers/{id}/';
