/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Adjustment } from '../../models/adjustment';
import { PatchedAdjustmentRequest } from '../../models/patched-adjustment-request';

export interface InventoryAdjustmentsPartialUpdate$FormData$Params {

/**
 * A unique integer value identifying this adjustment.
 */
  id: number;
      body?: PatchedAdjustmentRequest
}

export function inventoryAdjustmentsPartialUpdate$FormData(http: HttpClient, rootUrl: string, params: InventoryAdjustmentsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
  const rb = new RequestBuilder(rootUrl, inventoryAdjustmentsPartialUpdate$FormData.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Adjustment>;
    })
  );
}

inventoryAdjustmentsPartialUpdate$FormData.PATH = '/api/inventory/adjustments/{id}/';
