/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReverseRequest } from '../../models/reverse-request';
import { StockCount } from '../../models/stock-count';

export interface InventoryCountsReverseCreate$XWwwFormUrlencoded$Params {

/**
 * A unique integer value identifying this stock count.
 */
  id: number;
      body: ReverseRequest
}

export function inventoryCountsReverseCreate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: InventoryCountsReverseCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
  const rb = new RequestBuilder(rootUrl, inventoryCountsReverseCreate$XWwwFormUrlencoded.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockCount>;
    })
  );
}

inventoryCountsReverseCreate$XWwwFormUrlencoded.PATH = '/api/inventory/counts/{id}/reverse/';
