/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportRequest } from '../../models/import-request';
import { ImportResult } from '../../models/import-result';

export interface InventoryAdjustmentsImportCreate$Params {

/**
 * A unique integer value identifying this adjustment.
 */
  id: number;
      body: ImportRequest
}

export function inventoryAdjustmentsImportCreate(http: HttpClient, rootUrl: string, params: InventoryAdjustmentsImportCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportResult>> {
  const rb = new RequestBuilder(rootUrl, inventoryAdjustmentsImportCreate.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportResult>;
    })
  );
}

inventoryAdjustmentsImportCreate.PATH = '/api/inventory/adjustments/{id}/import/';
