/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedStockInRequest } from '../../models/patched-stock-in-request';
import { StockIn } from '../../models/stock-in';

export interface InventoryStockInsPartialUpdate$Json$Params {

/**
 * A unique integer value identifying this stock in.
 */
  id: number;
      body?: PatchedStockInRequest
}

export function inventoryStockInsPartialUpdate$Json(http: HttpClient, rootUrl: string, params: InventoryStockInsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
  const rb = new RequestBuilder(rootUrl, inventoryStockInsPartialUpdate$Json.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockIn>;
    })
  );
}

inventoryStockInsPartialUpdate$Json.PATH = '/api/inventory/stock-ins/{id}/';
