/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Adjustment } from '../../models/adjustment';
import { AdjustmentRequest } from '../../models/adjustment-request';

export interface InventoryAdjustmentsCreate$XWwwFormUrlencoded$Params {
      body: AdjustmentRequest
}

export function inventoryAdjustmentsCreate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: InventoryAdjustmentsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
  const rb = new RequestBuilder(rootUrl, inventoryAdjustmentsCreate$XWwwFormUrlencoded.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Adjustment>;
    })
  );
}

inventoryAdjustmentsCreate$XWwwFormUrlencoded.PATH = '/api/inventory/adjustments/';
