/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StockCount } from '../../models/stock-count';
import { StockCountRequest } from '../../models/stock-count-request';

export interface InventoryCountsCreate$Json$Params {
      body: StockCountRequest
}

export function inventoryCountsCreate$Json(http: HttpClient, rootUrl: string, params: InventoryCountsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
  const rb = new RequestBuilder(rootUrl, inventoryCountsCreate$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockCount>;
    })
  );
}

inventoryCountsCreate$Json.PATH = '/api/inventory/counts/';
