/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StockIn } from '../../models/stock-in';
import { StockInRequest } from '../../models/stock-in-request';

export interface InventoryStockInsCreate$Json$Params {
      body: StockInRequest
}

export function inventoryStockInsCreate$Json(http: HttpClient, rootUrl: string, params: InventoryStockInsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
  const rb = new RequestBuilder(rootUrl, inventoryStockInsCreate$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockIn>;
    })
  );
}

inventoryStockInsCreate$Json.PATH = '/api/inventory/stock-ins/';
