/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StockIn } from '../../models/stock-in';

export interface InventoryStockInsPostCreate$Params {

/**
 * A unique integer value identifying this stock in.
 */
  id: number;
}

export function inventoryStockInsPostCreate(http: HttpClient, rootUrl: string, params: InventoryStockInsPostCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
  const rb = new RequestBuilder(rootUrl, inventoryStockInsPostCreate.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockIn>;
    })
  );
}

inventoryStockInsPostCreate.PATH = '/api/inventory/stock-ins/{id}/post/';
