/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdjustmentLine } from '../models/adjustment-line';
import { DirectionEnum } from '../models/direction-enum';
import { DraftPostedStatusEnum } from '../models/draft-posted-status-enum';
import { ReasonEnum } from '../models/reason-enum';

/**
 * Header fields every stock document shares.
 *
 * Lines are sent whole: on update, a `lines` list replaces what was there.
 * Leave `lines` out to change the header only.
 */
export interface Adjustment {
  direction: DirectionEnum;
  doc_date?: string;
  id: number;
  lines?: Array<AdjustmentLine>;
  note?: string;
  number: string;
  posted_at: string | null;
  posted_by: number | null;
  posted_by_name: string | null;
  reason: ReasonEnum;
  reversed_by_number: string | null;
  reverses: number | null;
  reverses_number: string | null;
  status: DraftPostedStatusEnum;

  /**
   * For a return to, or a replacement from, a supplier.
   */
  supplier?: number | null;
  supplier_name: string | null;
}
