/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdjustmentLineRequest } from '../models/adjustment-line-request';
import { ReasonEnum } from '../models/reason-enum';

/**
 * Header fields every stock document shares.
 *
 * Lines are sent whole: on update, a `lines` list replaces what was there.
 * Leave `lines` out to change the header only.
 */
export interface AdjustmentRequest {
  doc_date?: string;
  lines?: Array<AdjustmentLineRequest>;
  note?: string;
  reason: ReasonEnum;

  /**
   * For a return to, or a replacement from, a supplier.
   */
  supplier?: number | null;
}
