/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The four columns a balance is aged into, by the days since its invoice.
 */
export interface Aged {
  credit_limit: string;
  d0_30: string;
  d31_60: string;
  d61_90: string;
  over_90: string;
  owed: string;

  /**
   * The limit less what is owed; below zero when over it.
   */
  room_left: string;
}
