/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BrandRequest {
  country?: string;
  display_order?: number;
  is_active?: boolean;
  logo?: Blob | null;
  name: string;
  name_kh?: string;
}
