/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashToday {

  /**
   * Cash customer payments posted today.
   */
  payments: string;

  /**
   * Cash refunds posted today.
   */
  refunds: string;

  /**
   * Cash kept from today's sales, after change.
   */
  sales: string;
  total: string;
}
