/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategorySales {

  /**
   * A main category; null for Other.
   */
  category: number | null;
  name: string;
  sales: string;

  /**
   * Its share of the day's sales.
   */
  share: string | null;
}
