/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryRequest {
  code: string;
  description?: string;
  display_order?: number;
  image?: Blob | null;
  is_active?: boolean;
  name: string;
  name_kh?: string;
  parent?: number | null;
}
