/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenderInputRequest } from '../models/tender-input-request';
export interface CompleteRequest {
  tenders?: Array<TenderInputRequest>;
}
