/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * What the sign-in page may show before anyone signs in: what is printed on
 * every receipt anyway, and nothing else.
 */
export interface CompanyBrand {
  address: string;
  logo: string | null;
  name: string;
  name_kh: string;
}
