/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyEnum } from './currency-enum';

/**
 * Each possible value of `CurrencyEnum`
 */
export const CURRENCY_ENUM: CurrencyEnum[] = [
  'USD',
  'KHR'
];