/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditStatusEnum } from '../models/credit-status-enum';
import { OpenInvoice } from '../models/open-invoice';

/**
 * What a customer owes, worked out now — never stored.
 */
export interface CustomerAccount {
  balance: string;
  code: string;
  credit_limit: string;
  credit_status: CreditStatusEnum;
  customer: number;
  name: string;
  open_invoices: Array<OpenInvoice>;
  payment_terms_days: number;
  room_left: string;
}
