/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditStatusEnum } from '../models/credit-status-enum';
import { PriceTierEnum } from '../models/price-tier-enum';

/**
 * Small payload for the till's Choose customer dialog.
 */
export interface CustomerLookup {

  /**
   * Leave blank to let the system number it.
   */
  code?: string;

  /**
   * In US dollars.
   */
  credit_limit?: string;
  credit_status: CreditStatusEnum;
  id: number;

  /**
   * The walk-in customer. Exactly one, created by seed.
   */
  is_system: boolean;
  name: string;

  /**
   * Days. Sets the due date on each credit sale.
   */
  payment_terms_days?: number;
  phone?: string;

  /**
   * Loaded automatically at checkout.
   *
   * * `RETAIL` - Retail
   * * `WHOLESALE` - Wholesale
   */
  price_tier?: PriceTierEnum;

  /**
   * Used in dropdowns and reports.
   */
  short_name?: string;
}
