/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DailySalesSummary } from '../models/daily-sales-summary';
import { SalesDay } from '../models/sales-day';
import { SalesSeller } from '../models/sales-seller';
import { SalesTender } from '../models/sales-tender';
export interface DailySales {

  /**
   * Newest day first; days without sales left out.
   */
  by_day: Array<SalesDay>;
  by_seller: Array<SalesSeller>;
  by_tender: Array<SalesTender>;
  date_from: string;
  date_to: string;

  /**
   * Whose sales; null for everyone's.
   */
  seller: number | null;
  summary: DailySalesSummary;
}
