/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DailySalesSummary {
  average: string;

  /**
   * Null unless the user may see cost.
   */
  cost: string | null;
  discount: string;
  invoices: number;

  /**
   * Profit as a share of sales. Null unless the user may see cost.
   */
  margin: string | null;

  /**
   * Null unless the user may see cost.
   */
  profit: string | null;
  returns_count: number;

  /**
   * Returns posted in the period, shown apart from the sales.
   */
  returns_total: string;
  sales: string;

  /**
   * Each sale at its own stamped rate.
   */
  sales_khr: string;
}
