/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Aged } from '../models/aged';
import { ReceivableRow } from '../models/receivable-row';
export interface DashboardOwed {

  /**
   * Customers who owe but are not listed.
   */
  more: number;
  over_90: string;
  owed: string;

  /**
   * The customers who owe most.
   */
  rows: Array<ReceivableRow>;

  /**
   * Everyone who owes.
   */
  totals: Aged;
}
