/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CashToday } from '../models/cash-today';
import { DashboardOwed } from '../models/dashboard-owed';
import { DashboardSales } from '../models/dashboard-sales';
import { DashboardStock } from '../models/dashboard-stock';
import { QuotationsDue } from '../models/quotations-due';
import { WarrantyOpen } from '../models/warranty-open';

/**
 * Each part is null when the user may not see it.
 */
export interface Dashboard {
  as_at: string;

  /**
   * report.sales.all. Not a drawer count.
   */
  cash_today: CashToday | null;

  /**
   * sell. Every till's.
   */
  held_sales: number | null;

  /**
   * report.receivables.
   */
  owed: DashboardOwed | null;

  /**
   * quotation.view.
   */
  quotations: QuotationsDue | null;

  /**
   * report.sales.all, or .own for their own.
   */
  sales: DashboardSales | null;

  /**
   * report.stock.
   */
  stock: DashboardStock | null;

  /**
   * warranty.view.
   */
  warranty: WarrantyOpen | null;
}
