/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardDay {
  date: string;
  sales: string;

  /**
   * Its share of the week's best day, for the bar's height.
   */
  share: string;
}
