/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardToday {
  average: string;
  invoices: number;

  /**
   * Profit as a share of sales. Null unless the user may see cost.
   */
  margin: string | null;

  /**
   * Null unless the user may see cost.
   */
  profit: string | null;
  sales: string;

  /**
   * Each sale at its own stamped rate.
   */
  sales_khr: string;
}
