/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LowStock } from '../models/low-stock';
export interface DashboardStock {

  /**
   * At or below the reorder level, out of stock included.
   */
  below_reorder: number;

  /**
   * Below reorder but not listed.
   */
  more: number;
  out_of_stock: number;
  products: number;

  /**
   * Out of stock first, then by code.
   */
  running_low: Array<LowStock>;

  /**
   * All stock at average cost. Null unless the user may see cost.
   */
  value: string | null;
}
