/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategorySales } from '../models/category-sales';
import { DashboardDay } from '../models/dashboard-day';
import { DashboardToday } from '../models/dashboard-today';
import { RecentSale } from '../models/recent-sale';
export interface DashboardSales {

  /**
   * Today; the biggest four, then Other.
   */
  by_category: Array<CategorySales>;

  /**
   * Oldest first; a day without sales is 0.00.
   */
  last_7_days: Array<DashboardDay>;

  /**
   * The last five completed sales, newest first.
   */
  recent: Array<RecentSale>;

  /**
   * Whose sales; null for the whole shop.
   */
  seller: number | null;
  today: DashboardToday;
}
