/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `QUOTATION` - Quotation
 * * `INVOICE` - Invoice
 * * `PAYMENT` - Customer payment
 * * `RETURN` - Return
 * * `STOCK_IN` - Stock in
 * * `ADJUSTMENT` - Adjustment
 * * `COUNT` - Stock count
 * * `WARRANTY` - Warranty claim
 * * `CUSTOMER` - Customer
 * * `SUPPLIER` - Supplier
 */
export type DocTypeEnum = 'QUOTATION' | 'INVOICE' | 'PAYMENT' | 'RETURN' | 'STOCK_IN' | 'ADJUSTMENT' | 'COUNT' | 'WARRANTY' | 'CUSTOMER' | 'SUPPLIER';

