/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocTypeEnum } from '../models/doc-type-enum';
export interface DocumentCounter {
  doc_type: DocTypeEnum;
  id: number;
  next_number: number;
  next_value: string;
  prefix: string;
}
