/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExchangeRate {
  created_at: string;
  effective_date: string;
  id: number;
  is_in_use: boolean;
  note?: string;

  /**
   * Riel per one US dollar.
   */
  rate: string;
  set_by: string | null;
}
