/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImportRequest {

  /**
   * False checks the file and adds nothing.
   */
  commit?: boolean;
  file: Blob;
  has_header?: boolean;

  /**
   * Replace the lines already on the draft instead of adding to them.
   */
  replace?: boolean;
}
