/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `HELD` - Held
 * * `COMPLETED` - Completed
 * * `VOID` - Void
 */
export type InvoiceStatusEnum = 'HELD' | 'COMPLETED' | 'VOID';

