/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { DiscountTypeEnum } from '../models/discount-type-enum';
export interface InvoiceLineRequest {
  discount_type?: (DiscountTypeEnum | BlankEnum);

  /**
   * Percent (0–15), or dollars off each unit.
   */
  discount_value?: string;
  product?: number;
  quantity: string;
  quote_line?: number | null;
}
