/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvoiceLine } from '../models/invoice-line';
import { InvoiceStatusEnum } from '../models/invoice-status-enum';
import { InvoiceTender } from '../models/invoice-tender';
import { PriceTierEnum } from '../models/price-tier-enum';

/**
 * A held sale is written through this. Completing and voiding are actions.
 */
export interface Invoice {
  change_due: string;
  change_khr: string;
  change_usd: string;

  /**
   * Null unless the user may see cost.
   */
  cost_total: string | null;
  customer: number;
  customer_name: string;
  discount_total: string;
  due_date: string | null;
  exchange_rate: string | null;
  held_total: string;
  hold_label?: string;
  id: number;
  lines?: Array<InvoiceLine>;
  number: string | null;
  on_credit: string;
  paid_now: string;
  price_tier: PriceTierEnum;

  /**
   * Null unless the user may see cost.
   */
  profit: string | null;
  quotation?: number | null;
  quotation_number: string | null;
  rounding: string;
  sale_date: string | null;
  seller: number | null;
  seller_name: string | null;
  status: InvoiceStatusEnum;
  tenders: Array<InvoiceTender>;
  total: string;
  total_khr: string | null;
  void_reason: string;
  voided_at: string | null;
  voided_by_name: string | null;
  walk_in_name?: string;
  walk_in_phone?: string;
}
