/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvoiceStatusEnum } from './invoice-status-enum';

/**
 * Each possible value of `InvoiceStatusEnum`
 */
export const INVOICE_STATUS_ENUM: InvoiceStatusEnum[] = [
  'HELD',
  'COMPLETED',
  'VOID'
];