/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyEnum } from '../models/currency-enum';
import { TenderKindEnum } from '../models/tender-kind-enum';
export interface InvoiceTender {

  /**
   * In its own currency.
   */
  amount: string;
  amount_usd: string;
  currency?: CurrencyEnum;
  kind: TenderKindEnum;
  reference?: string;
}
