/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OpenInvoice {
  balance: string;
  credited: string;
  due_date: string | null;
  id: number;
  number: string;
  on_credit: string;
  overdue: boolean;
  paid: string;
  sale_date: string;
}
