/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StockIn } from '../models/stock-in';
export interface PaginatedStockInList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<StockIn>;
}
