/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentCounter } from '../models/document-counter';
export interface PaginatedDocumentCounterList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<DocumentCounter>;
}
