/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WarrantyClaim } from '../models/warranty-claim';
export interface PaginatedWarrantyClaimList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<WarrantyClaim>;
}
