/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Supplier } from '../models/supplier';
export interface PaginatedSupplierList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Supplier>;
}
