/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Invoice } from '../models/invoice';
export interface PaginatedInvoiceList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Invoice>;
}
