/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Brand } from '../models/brand';
export interface PaginatedBrandList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Brand>;
}
