/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StockMovement } from '../models/stock-movement';
export interface PaginatedStockMovementList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<StockMovement>;
}
