/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StockCount } from '../models/stock-count';
export interface PaginatedStockCountList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<StockCount>;
}
