/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface PaginatedUserList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<User>;
}
