/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Unit } from '../models/unit';
export interface PaginatedUnitList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Unit>;
}
