/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Quotation } from '../models/quotation';
export interface PaginatedQuotationList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Quotation>;
}
