/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaidByEnum } from './paid-by-enum';

/**
 * Each possible value of `PaidByEnum`
 */
export const PAID_BY_ENUM: PaidByEnum[] = [
  'CASH',
  'KHQR',
  'CREDIT',
  'MIXED'
];