/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `CASH` - Cash
 * * `KHQR` - KHQR
 * * `CREDIT` - Credit
 * * `MIXED` - Mixed
 */
export type PaidByEnum = 'CASH' | 'KHQR' | 'CREDIT' | 'MIXED';

