/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PatchedExchangeRateRequest {
  effective_date?: string;
  note?: string;

  /**
   * Riel per one US dollar.
   */
  rate?: string;
}
