/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentTenderEnum } from './payment-tender-enum';

/**
 * Each possible value of `PaymentTenderEnum`
 */
export const PAYMENT_TENDER_ENUM: PaymentTenderEnum[] = [
  'CASH',
  'KHQR',
  'BANK'
];