/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentStatusEnum } from './payment-status-enum';

/**
 * Each possible value of `PaymentStatusEnum`
 */
export const PAYMENT_STATUS_ENUM: PaymentStatusEnum[] = [
  'POSTED',
  'VOID'
];