/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentNoteRequest {
  image?: Blob | null;
  is_active?: boolean;
  payment_info?: string;
  payment_type: string;
  row_order?: number;
}
