/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `CASH` - Cash
 * * `KHQR` - KHQR
 * * `BANK` - Bank transfer
 */
export type PaymentTenderEnum = 'CASH' | 'KHQR' | 'BANK';

