/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PriceTierEnum } from './price-tier-enum';

/**
 * Each possible value of `PriceTierEnum`
 */
export const PRICE_TIER_ENUM: PriceTierEnum[] = [
  'RETAIL',
  'WHOLESALE'
];