/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Product {
  avg_cost: string | null;

  /**
   * Leave empty if the product has none.
   */
  barcode?: string | null;
  brand?: number | null;
  brand_name: string | null;
  category: number;
  category_name: string;
  code: string;
  description?: string;
  display_order?: number;
  id: number;
  image?: string | null;
  is_active?: boolean;
  is_out_of_stock: boolean;

  /**
   * Blocks line discounting at the till.
   */
  is_price_fixed?: boolean;
  model_no?: string;
  name: string;
  name_kh?: string;
  needs_reorder: boolean;
  notes?: string;
  origin_country?: string;
  qty_on_hand: string;
  reorder_level?: string;
  reorder_qty?: string;
  retail_price?: string;

  /**
   * Where it sits in the shop, e.g. A3-2. Count sheets sort by it.
   */
  shelf_location?: string;

  /**
   * Must fit one receipt line.
   */
  short_name?: string;
  stock_value: string | null;

  /**
   * Off for services and labour, which have no quantity.
   */
  track_stock?: boolean;
  unit: number;
  unit_name: string;

  /**
   * Zero means none. Printed on the receipt.
   */
  warranty_months?: number;
  wholesale_price?: string;
}
