/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Runs the model's clean() on the instance as it would be saved.
 *
 * The rules are written once, on the model, and hold for the API the same as
 * for the Django admin.
 */
export interface ProductSupplier {
  id: number;

  /**
   * The supplier to buy from first. One per product.
   */
  is_preferred?: boolean;
  notes?: string;

  /**
   * Units of the product in the supplier's usual pack.
   */
  pack_size?: string;
  product: number;
  product_code: string;
  product_name: string;
  supplier: number;
  supplier_code: string;
  supplier_name: string;

  /**
   * The supplier's own code for this product.
   */
  supplier_sku?: string;
}
