/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlankEnum } from '../models/blank-enum';
import { DiscountTypeEnum } from '../models/discount-type-enum';
export interface QuotationLine {
  discount_type?: (DiscountTypeEnum | BlankEnum);

  /**
   * Percent (0–15), or dollars off each unit.
   */
  discount_value?: string;
  id: number;
  line_total: string;
  net_price: string;
  product: number;
  product_code: string;
  product_name: string;
  qty_invoiced: string;
  quantity: string;
  remaining: string;
  unit_name: string;
  unit_price: string;
}
