/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PriceTierEnum } from '../models/price-tier-enum';
import { QuotationLine } from '../models/quotation-line';
import { QuoteStatusEnum } from '../models/quote-status-enum';

/**
 * Lines are sent whole: on update, a `lines` list replaces what was there.
 * Leave `lines` out to change the header only.
 */
export interface Quotation {
  accepted_at: string | null;
  created_by_name: string | null;
  customer: number;

  /**
   * Address, district and province on one line.
   */
  customer_address: string;
  customer_name: string;
  customer_phone: string;
  id: number;
  invoiced_total: string;
  is_expired: boolean;
  lines?: Array<QuotationLine>;
  note?: string;
  number: string;
  price_tier: PriceTierEnum;
  quote_date?: string;
  remaining_total: string;
  status: QuoteStatusEnum;
  terms?: string;
  total: string;
  valid_until?: string;
}
