/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuotationsDue {

  /**
   * Of those, past their valid-until date.
   */
  expired: number;

  /**
   * Of those, valid for 7 days or less.
   */
  expiring: number;

  /**
   * Sent and not yet answered.
   */
  sent: number;
}
