/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `DRAFT` - Draft
 * * `SENT` - Sent
 * * `ACCEPTED` - Accepted
 * * `REJECTED` - Rejected
 * * `INVOICED` - Invoiced
 */
export type QuoteStatusEnum = 'DRAFT' | 'SENT' | 'ACCEPTED' | 'REJECTED' | 'INVOICED';

