/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The four columns a balance is aged into, by the days since its invoice.
 */
export interface ReceivableRow {
  code: string;
  credit_limit: string;
  customer: number;
  d0_30: string;
  d31_60: string;
  d61_90: string;
  name: string;
  on_hold: boolean;
  over_90: string;
  over_limit: boolean;

  /**
   * An open invoice is past its due date.
   */
  overdue: boolean;
  owed: string;

  /**
   * The limit less what is owed; below zero when over it.
   */
  room_left: string;
}
