/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReceivablesSummary {

  /**
   * Posted payments dated this month.
   */
  collected_this_month: string;

  /**
   * Customers over their limit or on credit hold.
   */
  flagged: Array<string>;
  owed: string;

  /**
   * At today's rate; null when there is none.
   */
  owed_khr: string | null;

  /**
   * Owed on invoices more than 60 days old.
   */
  past_60: string;
  past_60_share: string | null;
  rate: string | null;
}
