/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReceiptPaperWidthEnum } from './receipt-paper-width-enum';

/**
 * Each possible value of `ReceiptPaperWidthEnum`
 */
export const RECEIPT_PAPER_WIDTH_ENUM: ReceiptPaperWidthEnum[] = [
  '80mm',
  '58mm',
  'A5'
];