/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CountEntryRequest } from '../models/count-entry-request';
export interface RecordCountsRequest {
  lines: Array<CountEntryRequest>;
}
