/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RefundMethodEnum } from './refund-method-enum';

/**
 * Each possible value of `RefundMethodEnum`
 */
export const REFUND_METHOD_ENUM: RefundMethodEnum[] = [
  'CASH',
  'KHQR'
];