/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReturnLine {

  /**
   * Off for a faulty item: it does not go back into stock.
   */
  fit_to_sell?: boolean;
  id: number;
  invoice_line: number;
  line_total: string;
  product_code: string;
  product_name: string;
  quantity: string;
  sold: string;
  unit_price: string;
}
