/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReturnLineRequest {

  /**
   * Off for a faulty item: it does not go back into stock.
   */
  fit_to_sell?: boolean;
  invoice_line: number;
  quantity: string;
}
