/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleEnum } from './role-enum';

/**
 * Each possible value of `RoleEnum`
 */
export const ROLE_ENUM: RoleEnum[] = [
  'ADMIN',
  'SELLER'
];