/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * A refused refresh. `code` is session_replaced when the user has since
 * signed in on another device, session_ended for any other reason.
 */
export interface SessionEnded {
  code: string;
  detail: string;
}
