/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Me } from '../models/me';

/**
 * What login and refresh return. The refresh token itself is never in a
 * body — it rides in the httpOnly cookie.
 */
export interface Session {
  access: string;
  user: Me;
}
