/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StockInLine {
  brand_name: string | null;
  category_name: string;
  id: number;
  line_total: string;
  pack_cost: string;
  pack_size?: string;

  /**
   * Bought as, e.g. Carton. Blank means the product's own unit.
   */
  pack_unit?: number | null;
  pack_unit_name: string | null;
  packs: string;
  product: number;
  product_code: string;
  product_name: string;
  quantity: string;
  unit_cost: string;
  unit_name: string;
}
