/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `OUT` - Out of stock
 * * `REORDER` - Reorder
 * * `IDLE` - No movement
 * * `OK` - OK
 */
export type StockStatusEnum = 'OUT' | 'REORDER' | 'IDLE' | 'OK';

