/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DraftPostedStatusEnum } from '../models/draft-posted-status-enum';
import { StockInLine } from '../models/stock-in-line';

/**
 * Header fields every stock document shares.
 *
 * Lines are sent whole: on update, a `lines` list replaces what was there.
 * Leave `lines` out to change the header only.
 */
export interface StockIn {
  doc_date?: string;
  id: number;
  lines?: Array<StockInLine>;
  note?: string;
  number: string;
  posted_at: string | null;
  posted_by: number | null;
  posted_by_name: string | null;
  reversed_by_number: string | null;
  reverses: number | null;
  reverses_number: string | null;
  status: DraftPostedStatusEnum;
  supplier: number;
  supplier_name: string;

  /**
   * The supplier's invoice or delivery note number.
   */
  supplier_ref?: string;
  total: string;
}
