/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LastCount } from '../models/last-count';
export interface StockSummary {

  /**
   * At or below the reorder level, out of stock included.
   */
  below_reorder: number;
  last_count: LastCount | null;

  /**
   * Holding stock, nothing in or out for 90 days.
   */
  no_movement: number;

  /**
   * Null unless the user may see cost.
   */
  no_movement_value: string | null;
  out_of_stock: number;
  products: number;

  /**
   * All stock at average cost. Null unless the user may see cost.
   */
  value: string | null;
}
