/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Blind while counting: expected quantity and differences appear only
 * once the count is posted.
 */
export interface StockCountLine {
  brand_name: string | null;
  category_name: string;
  counted_at: string | null;
  counted_qty: string | null;
  difference: string | null;
  expected_qty: string | null;
  id: number;
  product: number;
  product_code: string;
  product_name: string;
  shelf_location: string;
  unit_cost: string | null;
  unit_name: string;
  value: string | null;
}
