/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StockInLineRequest {
  pack_cost: string;
  pack_size?: string;

  /**
   * Bought as, e.g. Carton. Blank means the product's own unit.
   */
  pack_unit?: number | null;
  packs: string;
  product: number;
}
