/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocTypeEnum } from '../models/doc-type-enum';
export interface StockMovement {
  avg_cost_after: string;
  doc_id: number;
  doc_number: string;
  doc_type: DocTypeEnum;
  id: number;
  is_reversal: boolean;
  movement_date: string;
  posted_at: string;
  posted_by_name: string | null;
  product: number;
  product_code: string;
  product_name: string;
  qty_after: string;
  quantity: string;
  reason: string;
  unit_cost: string;
  value: string;
}
