/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SupplierTypeEnum } from './supplier-type-enum';

/**
 * Each possible value of `SupplierTypeEnum`
 */
export const SUPPLIER_TYPE_ENUM: SupplierTypeEnum[] = [
  'MANUFACTURER',
  'IMPORTER',
  'DISTRIBUTOR',
  'WHOLESALER',
  'SERVICE_CENTRE',
  'LOCAL_MARKET'
];