/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `MANUFACTURER` - Manufacturer
 * * `IMPORTER` - Importer
 * * `DISTRIBUTOR` - Distributor
 * * `WHOLESALER` - Wholesaler
 * * `SERVICE_CENTRE` - Service centre
 * * `LOCAL_MARKET` - Local market
 */
export type SupplierTypeEnum = 'MANUFACTURER' | 'IMPORTER' | 'DISTRIBUTOR' | 'WHOLESALER' | 'SERVICE_CENTRE' | 'LOCAL_MARKET';

