/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenderKindEnum } from './tender-kind-enum';

/**
 * Each possible value of `TenderKindEnum`
 */
export const TENDER_KIND_ENUM: TenderKindEnum[] = [
  'CASH',
  'KHQR',
  'CREDIT'
];