/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * * `CASH` - Cash
 * * `KHQR` - KHQR
 * * `CREDIT` - Credit
 */
export type TenderKindEnum = 'CASH' | 'KHQR' | 'CREDIT';

