/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Unit {
  code: string;
  display_order?: number;
  id: number;
  is_active?: boolean;
  name: string;
  name_kh?: string;
}
