/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleEnum } from '../models/role-enum';
export interface UserCreated {
  created_at: string;
  full_name: string;
  full_name_kh?: string;
  id: number;
  initial_password: string;
  is_active?: boolean;
  last_login_at: string | null;
  must_change_password: boolean;
  phone?: string;
  role?: RoleEnum;
  username: string;
}
