/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleEnum } from '../models/role-enum';
export interface UserCreateRequest {
  full_name: string;
  full_name_kh?: string;
  is_active?: boolean;
  password?: string;
  phone?: string;
  role?: RoleEnum;
  username: string;
}
