/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimStatusEnum } from '../models/claim-status-enum';
export interface WarrantyClaim {

  /**
   * Null until the claim is edited.
   */
  changed_by_name: string | null;
  created_at: string;
  customer_name?: string;
  customer_phone?: string;
  expiry_date?: string | null;
  id: number;
  logged_by_name: string | null;
  note?: string;

  /**
   * Claimed after the warranty's end date.
   */
  out_of_warranty: boolean;
  product_code?: string;
  product_name: string;
  status?: ClaimStatusEnum;
  updated_at: string;

  /**
   * Zero when the item has none.
   */
  warranty_months?: number;

  /**
   * From the warranty card or the supplier's sticker.
   */
  warranty_number: string;
}
