/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimStatusEnum } from '../models/claim-status-enum';
export interface WarrantyClaimRequest {
  customer_name?: string;
  customer_phone?: string;
  expiry_date?: string | null;
  note?: string;
  product_code?: string;
  product_name: string;
  status?: ClaimStatusEnum;

  /**
   * Zero when the item has none.
   */
  warranty_months?: number;

  /**
   * From the warranty card or the supplier's sticker.
   */
  warranty_number: string;
}
