/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WarrantyOpen {

  /**
   * Received, sent for repair or ready for collection.
   */
  open: number;

  /**
   * Of those, claimed after the warranty ended.
   */
  out_of_warranty: number;
}
