/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Brand } from '../models/brand';
import { catalogueBrandsCreate$FormData } from '../fn/catalogue/catalogue-brands-create-form-data';
import { CatalogueBrandsCreate$FormData$Params } from '../fn/catalogue/catalogue-brands-create-form-data';
import { catalogueBrandsCreate$Json } from '../fn/catalogue/catalogue-brands-create-json';
import { CatalogueBrandsCreate$Json$Params } from '../fn/catalogue/catalogue-brands-create-json';
import { catalogueBrandsCreate$XWwwFormUrlencoded } from '../fn/catalogue/catalogue-brands-create-x-www-form-urlencoded';
import { CatalogueBrandsCreate$XWwwFormUrlencoded$Params } from '../fn/catalogue/catalogue-brands-create-x-www-form-urlencoded';
import { catalogueBrandsList } from '../fn/catalogue/catalogue-brands-list';
import { CatalogueBrandsList$Params } from '../fn/catalogue/catalogue-brands-list';
import { catalogueBrandsPartialUpdate$FormData } from '../fn/catalogue/catalogue-brands-partial-update-form-data';
import { CatalogueBrandsPartialUpdate$FormData$Params } from '../fn/catalogue/catalogue-brands-partial-update-form-data';
import { catalogueBrandsPartialUpdate$Json } from '../fn/catalogue/catalogue-brands-partial-update-json';
import { CatalogueBrandsPartialUpdate$Json$Params } from '../fn/catalogue/catalogue-brands-partial-update-json';
import { catalogueBrandsPartialUpdate$XWwwFormUrlencoded } from '../fn/catalogue/catalogue-brands-partial-update-x-www-form-urlencoded';
import { CatalogueBrandsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/catalogue/catalogue-brands-partial-update-x-www-form-urlencoded';
import { catalogueBrandsRetrieve } from '../fn/catalogue/catalogue-brands-retrieve';
import { CatalogueBrandsRetrieve$Params } from '../fn/catalogue/catalogue-brands-retrieve';
import { catalogueCategoriesCreate$FormData } from '../fn/catalogue/catalogue-categories-create-form-data';
import { CatalogueCategoriesCreate$FormData$Params } from '../fn/catalogue/catalogue-categories-create-form-data';
import { catalogueCategoriesCreate$Json } from '../fn/catalogue/catalogue-categories-create-json';
import { CatalogueCategoriesCreate$Json$Params } from '../fn/catalogue/catalogue-categories-create-json';
import { catalogueCategoriesCreate$XWwwFormUrlencoded } from '../fn/catalogue/catalogue-categories-create-x-www-form-urlencoded';
import { CatalogueCategoriesCreate$XWwwFormUrlencoded$Params } from '../fn/catalogue/catalogue-categories-create-x-www-form-urlencoded';
import { catalogueCategoriesList } from '../fn/catalogue/catalogue-categories-list';
import { CatalogueCategoriesList$Params } from '../fn/catalogue/catalogue-categories-list';
import { catalogueCategoriesPartialUpdate$FormData } from '../fn/catalogue/catalogue-categories-partial-update-form-data';
import { CatalogueCategoriesPartialUpdate$FormData$Params } from '../fn/catalogue/catalogue-categories-partial-update-form-data';
import { catalogueCategoriesPartialUpdate$Json } from '../fn/catalogue/catalogue-categories-partial-update-json';
import { CatalogueCategoriesPartialUpdate$Json$Params } from '../fn/catalogue/catalogue-categories-partial-update-json';
import { catalogueCategoriesPartialUpdate$XWwwFormUrlencoded } from '../fn/catalogue/catalogue-categories-partial-update-x-www-form-urlencoded';
import { CatalogueCategoriesPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/catalogue/catalogue-categories-partial-update-x-www-form-urlencoded';
import { catalogueCategoriesRetrieve } from '../fn/catalogue/catalogue-categories-retrieve';
import { CatalogueCategoriesRetrieve$Params } from '../fn/catalogue/catalogue-categories-retrieve';
import { catalogueProductsCreate$FormData } from '../fn/catalogue/catalogue-products-create-form-data';
import { CatalogueProductsCreate$FormData$Params } from '../fn/catalogue/catalogue-products-create-form-data';
import { catalogueProductsCreate$Json } from '../fn/catalogue/catalogue-products-create-json';
import { CatalogueProductsCreate$Json$Params } from '../fn/catalogue/catalogue-products-create-json';
import { catalogueProductsCreate$XWwwFormUrlencoded } from '../fn/catalogue/catalogue-products-create-x-www-form-urlencoded';
import { CatalogueProductsCreate$XWwwFormUrlencoded$Params } from '../fn/catalogue/catalogue-products-create-x-www-form-urlencoded';
import { catalogueProductsList } from '../fn/catalogue/catalogue-products-list';
import { CatalogueProductsList$Params } from '../fn/catalogue/catalogue-products-list';
import { catalogueProductsLookupList } from '../fn/catalogue/catalogue-products-lookup-list';
import { CatalogueProductsLookupList$Params } from '../fn/catalogue/catalogue-products-lookup-list';
import { catalogueProductsPartialUpdate$FormData } from '../fn/catalogue/catalogue-products-partial-update-form-data';
import { CatalogueProductsPartialUpdate$FormData$Params } from '../fn/catalogue/catalogue-products-partial-update-form-data';
import { catalogueProductsPartialUpdate$Json } from '../fn/catalogue/catalogue-products-partial-update-json';
import { CatalogueProductsPartialUpdate$Json$Params } from '../fn/catalogue/catalogue-products-partial-update-json';
import { catalogueProductsPartialUpdate$XWwwFormUrlencoded } from '../fn/catalogue/catalogue-products-partial-update-x-www-form-urlencoded';
import { CatalogueProductsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/catalogue/catalogue-products-partial-update-x-www-form-urlencoded';
import { catalogueProductsRetrieve } from '../fn/catalogue/catalogue-products-retrieve';
import { CatalogueProductsRetrieve$Params } from '../fn/catalogue/catalogue-products-retrieve';
import { catalogueUnitsCreate$FormData } from '../fn/catalogue/catalogue-units-create-form-data';
import { CatalogueUnitsCreate$FormData$Params } from '../fn/catalogue/catalogue-units-create-form-data';
import { catalogueUnitsCreate$Json } from '../fn/catalogue/catalogue-units-create-json';
import { CatalogueUnitsCreate$Json$Params } from '../fn/catalogue/catalogue-units-create-json';
import { catalogueUnitsCreate$XWwwFormUrlencoded } from '../fn/catalogue/catalogue-units-create-x-www-form-urlencoded';
import { CatalogueUnitsCreate$XWwwFormUrlencoded$Params } from '../fn/catalogue/catalogue-units-create-x-www-form-urlencoded';
import { catalogueUnitsList } from '../fn/catalogue/catalogue-units-list';
import { CatalogueUnitsList$Params } from '../fn/catalogue/catalogue-units-list';
import { catalogueUnitsPartialUpdate$FormData } from '../fn/catalogue/catalogue-units-partial-update-form-data';
import { CatalogueUnitsPartialUpdate$FormData$Params } from '../fn/catalogue/catalogue-units-partial-update-form-data';
import { catalogueUnitsPartialUpdate$Json } from '../fn/catalogue/catalogue-units-partial-update-json';
import { CatalogueUnitsPartialUpdate$Json$Params } from '../fn/catalogue/catalogue-units-partial-update-json';
import { catalogueUnitsPartialUpdate$XWwwFormUrlencoded } from '../fn/catalogue/catalogue-units-partial-update-x-www-form-urlencoded';
import { CatalogueUnitsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/catalogue/catalogue-units-partial-update-x-www-form-urlencoded';
import { catalogueUnitsRetrieve } from '../fn/catalogue/catalogue-units-retrieve';
import { CatalogueUnitsRetrieve$Params } from '../fn/catalogue/catalogue-units-retrieve';
import { Category } from '../models/category';
import { PaginatedBrandList } from '../models/paginated-brand-list';
import { PaginatedCategoryList } from '../models/paginated-category-list';
import { PaginatedProductList } from '../models/paginated-product-list';
import { PaginatedUnitList } from '../models/paginated-unit-list';
import { Product } from '../models/product';
import { ProductLookup } from '../models/product-lookup';
import { Unit } from '../models/unit';

@Injectable({ providedIn: 'root' })
export class CatalogueService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `catalogueBrandsList()` */
  static readonly CatalogueBrandsListPath = '/api/catalogue/brands/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueBrandsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueBrandsList$Response(params?: CatalogueBrandsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedBrandList>> {
    const obs = catalogueBrandsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueBrandsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueBrandsList(params?: CatalogueBrandsList$Params, context?: HttpContext): Observable<PaginatedBrandList> {
    const resp = this.catalogueBrandsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedBrandList>): PaginatedBrandList => r.body)
    );
  }

  /** Path part for operation `catalogueBrandsCreate()` */
  static readonly CatalogueBrandsCreatePath = '/api/catalogue/brands/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueBrandsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueBrandsCreate$Json$Response(params: CatalogueBrandsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Brand>> {
    const obs = catalogueBrandsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueBrandsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueBrandsCreate$Json(params: CatalogueBrandsCreate$Json$Params, context?: HttpContext): Observable<Brand> {
    const resp = this.catalogueBrandsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Brand>): Brand => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueBrandsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueBrandsCreate$XWwwFormUrlencoded$Response(params: CatalogueBrandsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Brand>> {
    const obs = catalogueBrandsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueBrandsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueBrandsCreate$XWwwFormUrlencoded(params: CatalogueBrandsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Brand> {
    const resp = this.catalogueBrandsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Brand>): Brand => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueBrandsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueBrandsCreate$FormData$Response(params: CatalogueBrandsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Brand>> {
    const obs = catalogueBrandsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueBrandsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueBrandsCreate$FormData(params: CatalogueBrandsCreate$FormData$Params, context?: HttpContext): Observable<Brand> {
    const resp = this.catalogueBrandsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Brand>): Brand => r.body)
    );
  }

  /** Path part for operation `catalogueBrandsRetrieve()` */
  static readonly CatalogueBrandsRetrievePath = '/api/catalogue/brands/{id}/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueBrandsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueBrandsRetrieve$Response(params: CatalogueBrandsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Brand>> {
    const obs = catalogueBrandsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueBrandsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueBrandsRetrieve(params: CatalogueBrandsRetrieve$Params, context?: HttpContext): Observable<Brand> {
    const resp = this.catalogueBrandsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Brand>): Brand => r.body)
    );
  }

  /** Path part for operation `catalogueBrandsPartialUpdate()` */
  static readonly CatalogueBrandsPartialUpdatePath = '/api/catalogue/brands/{id}/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueBrandsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueBrandsPartialUpdate$Json$Response(params: CatalogueBrandsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Brand>> {
    const obs = catalogueBrandsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueBrandsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueBrandsPartialUpdate$Json(params: CatalogueBrandsPartialUpdate$Json$Params, context?: HttpContext): Observable<Brand> {
    const resp = this.catalogueBrandsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Brand>): Brand => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueBrandsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueBrandsPartialUpdate$XWwwFormUrlencoded$Response(params: CatalogueBrandsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Brand>> {
    const obs = catalogueBrandsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueBrandsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueBrandsPartialUpdate$XWwwFormUrlencoded(params: CatalogueBrandsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Brand> {
    const resp = this.catalogueBrandsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Brand>): Brand => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueBrandsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueBrandsPartialUpdate$FormData$Response(params: CatalogueBrandsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Brand>> {
    const obs = catalogueBrandsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueBrandsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueBrandsPartialUpdate$FormData(params: CatalogueBrandsPartialUpdate$FormData$Params, context?: HttpContext): Observable<Brand> {
    const resp = this.catalogueBrandsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Brand>): Brand => r.body)
    );
  }

  /** Path part for operation `catalogueCategoriesList()` */
  static readonly CatalogueCategoriesListPath = '/api/catalogue/categories/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueCategoriesList()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueCategoriesList$Response(params?: CatalogueCategoriesList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedCategoryList>> {
    const obs = catalogueCategoriesList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueCategoriesList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueCategoriesList(params?: CatalogueCategoriesList$Params, context?: HttpContext): Observable<PaginatedCategoryList> {
    const resp = this.catalogueCategoriesList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedCategoryList>): PaginatedCategoryList => r.body)
    );
  }

  /** Path part for operation `catalogueCategoriesCreate()` */
  static readonly CatalogueCategoriesCreatePath = '/api/catalogue/categories/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueCategoriesCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueCategoriesCreate$Json$Response(params: CatalogueCategoriesCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
    const obs = catalogueCategoriesCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueCategoriesCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueCategoriesCreate$Json(params: CatalogueCategoriesCreate$Json$Params, context?: HttpContext): Observable<Category> {
    const resp = this.catalogueCategoriesCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Category>): Category => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueCategoriesCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueCategoriesCreate$XWwwFormUrlencoded$Response(params: CatalogueCategoriesCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
    const obs = catalogueCategoriesCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueCategoriesCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueCategoriesCreate$XWwwFormUrlencoded(params: CatalogueCategoriesCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Category> {
    const resp = this.catalogueCategoriesCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Category>): Category => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueCategoriesCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueCategoriesCreate$FormData$Response(params: CatalogueCategoriesCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
    const obs = catalogueCategoriesCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueCategoriesCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueCategoriesCreate$FormData(params: CatalogueCategoriesCreate$FormData$Params, context?: HttpContext): Observable<Category> {
    const resp = this.catalogueCategoriesCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Category>): Category => r.body)
    );
  }

  /** Path part for operation `catalogueCategoriesRetrieve()` */
  static readonly CatalogueCategoriesRetrievePath = '/api/catalogue/categories/{id}/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueCategoriesRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueCategoriesRetrieve$Response(params: CatalogueCategoriesRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
    const obs = catalogueCategoriesRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueCategoriesRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueCategoriesRetrieve(params: CatalogueCategoriesRetrieve$Params, context?: HttpContext): Observable<Category> {
    const resp = this.catalogueCategoriesRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Category>): Category => r.body)
    );
  }

  /** Path part for operation `catalogueCategoriesPartialUpdate()` */
  static readonly CatalogueCategoriesPartialUpdatePath = '/api/catalogue/categories/{id}/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueCategoriesPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueCategoriesPartialUpdate$Json$Response(params: CatalogueCategoriesPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
    const obs = catalogueCategoriesPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueCategoriesPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueCategoriesPartialUpdate$Json(params: CatalogueCategoriesPartialUpdate$Json$Params, context?: HttpContext): Observable<Category> {
    const resp = this.catalogueCategoriesPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Category>): Category => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueCategoriesPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueCategoriesPartialUpdate$XWwwFormUrlencoded$Response(params: CatalogueCategoriesPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
    const obs = catalogueCategoriesPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueCategoriesPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueCategoriesPartialUpdate$XWwwFormUrlencoded(params: CatalogueCategoriesPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Category> {
    const resp = this.catalogueCategoriesPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Category>): Category => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueCategoriesPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueCategoriesPartialUpdate$FormData$Response(params: CatalogueCategoriesPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
    const obs = catalogueCategoriesPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueCategoriesPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueCategoriesPartialUpdate$FormData(params: CatalogueCategoriesPartialUpdate$FormData$Params, context?: HttpContext): Observable<Category> {
    const resp = this.catalogueCategoriesPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Category>): Category => r.body)
    );
  }

  /** Path part for operation `catalogueProductsList()` */
  static readonly CatalogueProductsListPath = '/api/catalogue/products/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueProductsList$Response(params?: CatalogueProductsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedProductList>> {
    const obs = catalogueProductsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueProductsList(params?: CatalogueProductsList$Params, context?: HttpContext): Observable<PaginatedProductList> {
    const resp = this.catalogueProductsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedProductList>): PaginatedProductList => r.body)
    );
  }

  /** Path part for operation `catalogueProductsCreate()` */
  static readonly CatalogueProductsCreatePath = '/api/catalogue/products/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueProductsCreate$Json$Response(params: CatalogueProductsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    const obs = catalogueProductsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueProductsCreate$Json(params: CatalogueProductsCreate$Json$Params, context?: HttpContext): Observable<Product> {
    const resp = this.catalogueProductsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueProductsCreate$XWwwFormUrlencoded$Response(params: CatalogueProductsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    const obs = catalogueProductsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueProductsCreate$XWwwFormUrlencoded(params: CatalogueProductsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Product> {
    const resp = this.catalogueProductsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueProductsCreate$FormData$Response(params: CatalogueProductsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    const obs = catalogueProductsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueProductsCreate$FormData(params: CatalogueProductsCreate$FormData$Params, context?: HttpContext): Observable<Product> {
    const resp = this.catalogueProductsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

  /** Path part for operation `catalogueProductsRetrieve()` */
  static readonly CatalogueProductsRetrievePath = '/api/catalogue/products/{id}/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueProductsRetrieve$Response(params: CatalogueProductsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    const obs = catalogueProductsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueProductsRetrieve(params: CatalogueProductsRetrieve$Params, context?: HttpContext): Observable<Product> {
    const resp = this.catalogueProductsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

  /** Path part for operation `catalogueProductsPartialUpdate()` */
  static readonly CatalogueProductsPartialUpdatePath = '/api/catalogue/products/{id}/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueProductsPartialUpdate$Json$Response(params: CatalogueProductsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    const obs = catalogueProductsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueProductsPartialUpdate$Json(params: CatalogueProductsPartialUpdate$Json$Params, context?: HttpContext): Observable<Product> {
    const resp = this.catalogueProductsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueProductsPartialUpdate$XWwwFormUrlencoded$Response(params: CatalogueProductsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    const obs = catalogueProductsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueProductsPartialUpdate$XWwwFormUrlencoded(params: CatalogueProductsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Product> {
    const resp = this.catalogueProductsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueProductsPartialUpdate$FormData$Response(params: CatalogueProductsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    const obs = catalogueProductsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueProductsPartialUpdate$FormData(params: CatalogueProductsPartialUpdate$FormData$Params, context?: HttpContext): Observable<Product> {
    const resp = this.catalogueProductsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

  /** Path part for operation `catalogueProductsLookupList()` */
  static readonly CatalogueProductsLookupListPath = '/api/catalogue/products/lookup/';

  /**
   * Small payload for the till and stock line pickers.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueProductsLookupList()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueProductsLookupList$Response(params?: CatalogueProductsLookupList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductLookup>>> {
    const obs = catalogueProductsLookupList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Small payload for the till and stock line pickers.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueProductsLookupList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueProductsLookupList(params?: CatalogueProductsLookupList$Params, context?: HttpContext): Observable<Array<ProductLookup>> {
    const resp = this.catalogueProductsLookupList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ProductLookup>>): Array<ProductLookup> => r.body)
    );
  }

  /** Path part for operation `catalogueUnitsList()` */
  static readonly CatalogueUnitsListPath = '/api/catalogue/units/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueUnitsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueUnitsList$Response(params?: CatalogueUnitsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedUnitList>> {
    const obs = catalogueUnitsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueUnitsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueUnitsList(params?: CatalogueUnitsList$Params, context?: HttpContext): Observable<PaginatedUnitList> {
    const resp = this.catalogueUnitsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedUnitList>): PaginatedUnitList => r.body)
    );
  }

  /** Path part for operation `catalogueUnitsCreate()` */
  static readonly CatalogueUnitsCreatePath = '/api/catalogue/units/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueUnitsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueUnitsCreate$Json$Response(params: CatalogueUnitsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
    const obs = catalogueUnitsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueUnitsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueUnitsCreate$Json(params: CatalogueUnitsCreate$Json$Params, context?: HttpContext): Observable<Unit> {
    const resp = this.catalogueUnitsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Unit>): Unit => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueUnitsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueUnitsCreate$XWwwFormUrlencoded$Response(params: CatalogueUnitsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
    const obs = catalogueUnitsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueUnitsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueUnitsCreate$XWwwFormUrlencoded(params: CatalogueUnitsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Unit> {
    const resp = this.catalogueUnitsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Unit>): Unit => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueUnitsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueUnitsCreate$FormData$Response(params: CatalogueUnitsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
    const obs = catalogueUnitsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueUnitsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueUnitsCreate$FormData(params: CatalogueUnitsCreate$FormData$Params, context?: HttpContext): Observable<Unit> {
    const resp = this.catalogueUnitsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Unit>): Unit => r.body)
    );
  }

  /** Path part for operation `catalogueUnitsRetrieve()` */
  static readonly CatalogueUnitsRetrievePath = '/api/catalogue/units/{id}/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueUnitsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueUnitsRetrieve$Response(params: CatalogueUnitsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
    const obs = catalogueUnitsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueUnitsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  catalogueUnitsRetrieve(params: CatalogueUnitsRetrieve$Params, context?: HttpContext): Observable<Unit> {
    const resp = this.catalogueUnitsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Unit>): Unit => r.body)
    );
  }

  /** Path part for operation `catalogueUnitsPartialUpdate()` */
  static readonly CatalogueUnitsPartialUpdatePath = '/api/catalogue/units/{id}/';

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueUnitsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueUnitsPartialUpdate$Json$Response(params: CatalogueUnitsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
    const obs = catalogueUnitsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueUnitsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  catalogueUnitsPartialUpdate$Json(params: CatalogueUnitsPartialUpdate$Json$Params, context?: HttpContext): Observable<Unit> {
    const resp = this.catalogueUnitsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Unit>): Unit => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueUnitsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueUnitsPartialUpdate$XWwwFormUrlencoded$Response(params: CatalogueUnitsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
    const obs = catalogueUnitsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueUnitsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  catalogueUnitsPartialUpdate$XWwwFormUrlencoded(params: CatalogueUnitsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Unit> {
    const resp = this.catalogueUnitsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Unit>): Unit => r.body)
    );
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `catalogueUnitsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueUnitsPartialUpdate$FormData$Response(params: CatalogueUnitsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
    const obs = catalogueUnitsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * ?active=true or ?active=false narrows a list to live or retired rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `catalogueUnitsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  catalogueUnitsPartialUpdate$FormData(params: CatalogueUnitsPartialUpdate$FormData$Params, context?: HttpContext): Observable<Unit> {
    const resp = this.catalogueUnitsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Unit>): Unit => r.body)
    );
  }

}
