/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Adjustment } from '../models/adjustment';
import { ImportResult } from '../models/import-result';
import { inventoryAdjustmentsCreate$FormData } from '../fn/inventory/inventory-adjustments-create-form-data';
import { InventoryAdjustmentsCreate$FormData$Params } from '../fn/inventory/inventory-adjustments-create-form-data';
import { inventoryAdjustmentsCreate$Json } from '../fn/inventory/inventory-adjustments-create-json';
import { InventoryAdjustmentsCreate$Json$Params } from '../fn/inventory/inventory-adjustments-create-json';
import { inventoryAdjustmentsCreate$XWwwFormUrlencoded } from '../fn/inventory/inventory-adjustments-create-x-www-form-urlencoded';
import { InventoryAdjustmentsCreate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-adjustments-create-x-www-form-urlencoded';
import { inventoryAdjustmentsDestroy } from '../fn/inventory/inventory-adjustments-destroy';
import { InventoryAdjustmentsDestroy$Params } from '../fn/inventory/inventory-adjustments-destroy';
import { inventoryAdjustmentsImportCreate } from '../fn/inventory/inventory-adjustments-import-create';
import { InventoryAdjustmentsImportCreate$Params } from '../fn/inventory/inventory-adjustments-import-create';
import { inventoryAdjustmentsList } from '../fn/inventory/inventory-adjustments-list';
import { InventoryAdjustmentsList$Params } from '../fn/inventory/inventory-adjustments-list';
import { inventoryAdjustmentsPartialUpdate$FormData } from '../fn/inventory/inventory-adjustments-partial-update-form-data';
import { InventoryAdjustmentsPartialUpdate$FormData$Params } from '../fn/inventory/inventory-adjustments-partial-update-form-data';
import { inventoryAdjustmentsPartialUpdate$Json } from '../fn/inventory/inventory-adjustments-partial-update-json';
import { InventoryAdjustmentsPartialUpdate$Json$Params } from '../fn/inventory/inventory-adjustments-partial-update-json';
import { inventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded } from '../fn/inventory/inventory-adjustments-partial-update-x-www-form-urlencoded';
import { InventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-adjustments-partial-update-x-www-form-urlencoded';
import { inventoryAdjustmentsPostCreate } from '../fn/inventory/inventory-adjustments-post-create';
import { InventoryAdjustmentsPostCreate$Params } from '../fn/inventory/inventory-adjustments-post-create';
import { inventoryAdjustmentsRetrieve } from '../fn/inventory/inventory-adjustments-retrieve';
import { InventoryAdjustmentsRetrieve$Params } from '../fn/inventory/inventory-adjustments-retrieve';
import { inventoryAdjustmentsReverseCreate$FormData } from '../fn/inventory/inventory-adjustments-reverse-create-form-data';
import { InventoryAdjustmentsReverseCreate$FormData$Params } from '../fn/inventory/inventory-adjustments-reverse-create-form-data';
import { inventoryAdjustmentsReverseCreate$Json } from '../fn/inventory/inventory-adjustments-reverse-create-json';
import { InventoryAdjustmentsReverseCreate$Json$Params } from '../fn/inventory/inventory-adjustments-reverse-create-json';
import { inventoryAdjustmentsReverseCreate$XWwwFormUrlencoded } from '../fn/inventory/inventory-adjustments-reverse-create-x-www-form-urlencoded';
import { InventoryAdjustmentsReverseCreate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-adjustments-reverse-create-x-www-form-urlencoded';
import { inventoryCountsCreate$FormData } from '../fn/inventory/inventory-counts-create-form-data';
import { InventoryCountsCreate$FormData$Params } from '../fn/inventory/inventory-counts-create-form-data';
import { inventoryCountsCreate$Json } from '../fn/inventory/inventory-counts-create-json';
import { InventoryCountsCreate$Json$Params } from '../fn/inventory/inventory-counts-create-json';
import { inventoryCountsCreate$XWwwFormUrlencoded } from '../fn/inventory/inventory-counts-create-x-www-form-urlencoded';
import { InventoryCountsCreate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-counts-create-x-www-form-urlencoded';
import { inventoryCountsDestroy } from '../fn/inventory/inventory-counts-destroy';
import { InventoryCountsDestroy$Params } from '../fn/inventory/inventory-counts-destroy';
import { inventoryCountsList } from '../fn/inventory/inventory-counts-list';
import { InventoryCountsList$Params } from '../fn/inventory/inventory-counts-list';
import { inventoryCountsPartialUpdate$FormData } from '../fn/inventory/inventory-counts-partial-update-form-data';
import { InventoryCountsPartialUpdate$FormData$Params } from '../fn/inventory/inventory-counts-partial-update-form-data';
import { inventoryCountsPartialUpdate$Json } from '../fn/inventory/inventory-counts-partial-update-json';
import { InventoryCountsPartialUpdate$Json$Params } from '../fn/inventory/inventory-counts-partial-update-json';
import { inventoryCountsPartialUpdate$XWwwFormUrlencoded } from '../fn/inventory/inventory-counts-partial-update-x-www-form-urlencoded';
import { InventoryCountsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-counts-partial-update-x-www-form-urlencoded';
import { inventoryCountsPostCreate } from '../fn/inventory/inventory-counts-post-create';
import { InventoryCountsPostCreate$Params } from '../fn/inventory/inventory-counts-post-create';
import { inventoryCountsRecordCreate$FormData } from '../fn/inventory/inventory-counts-record-create-form-data';
import { InventoryCountsRecordCreate$FormData$Params } from '../fn/inventory/inventory-counts-record-create-form-data';
import { inventoryCountsRecordCreate$Json } from '../fn/inventory/inventory-counts-record-create-json';
import { InventoryCountsRecordCreate$Json$Params } from '../fn/inventory/inventory-counts-record-create-json';
import { inventoryCountsRecordCreate$XWwwFormUrlencoded } from '../fn/inventory/inventory-counts-record-create-x-www-form-urlencoded';
import { InventoryCountsRecordCreate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-counts-record-create-x-www-form-urlencoded';
import { inventoryCountsRetrieve } from '../fn/inventory/inventory-counts-retrieve';
import { InventoryCountsRetrieve$Params } from '../fn/inventory/inventory-counts-retrieve';
import { inventoryCountsReverseCreate$FormData } from '../fn/inventory/inventory-counts-reverse-create-form-data';
import { InventoryCountsReverseCreate$FormData$Params } from '../fn/inventory/inventory-counts-reverse-create-form-data';
import { inventoryCountsReverseCreate$Json } from '../fn/inventory/inventory-counts-reverse-create-json';
import { InventoryCountsReverseCreate$Json$Params } from '../fn/inventory/inventory-counts-reverse-create-json';
import { inventoryCountsReverseCreate$XWwwFormUrlencoded } from '../fn/inventory/inventory-counts-reverse-create-x-www-form-urlencoded';
import { InventoryCountsReverseCreate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-counts-reverse-create-x-www-form-urlencoded';
import { inventoryMovementsList } from '../fn/inventory/inventory-movements-list';
import { InventoryMovementsList$Params } from '../fn/inventory/inventory-movements-list';
import { inventoryMovementsRetrieve } from '../fn/inventory/inventory-movements-retrieve';
import { InventoryMovementsRetrieve$Params } from '../fn/inventory/inventory-movements-retrieve';
import { inventoryStockInsCreate$FormData } from '../fn/inventory/inventory-stock-ins-create-form-data';
import { InventoryStockInsCreate$FormData$Params } from '../fn/inventory/inventory-stock-ins-create-form-data';
import { inventoryStockInsCreate$Json } from '../fn/inventory/inventory-stock-ins-create-json';
import { InventoryStockInsCreate$Json$Params } from '../fn/inventory/inventory-stock-ins-create-json';
import { inventoryStockInsCreate$XWwwFormUrlencoded } from '../fn/inventory/inventory-stock-ins-create-x-www-form-urlencoded';
import { InventoryStockInsCreate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-stock-ins-create-x-www-form-urlencoded';
import { inventoryStockInsDestroy } from '../fn/inventory/inventory-stock-ins-destroy';
import { InventoryStockInsDestroy$Params } from '../fn/inventory/inventory-stock-ins-destroy';
import { inventoryStockInsImportCreate } from '../fn/inventory/inventory-stock-ins-import-create';
import { InventoryStockInsImportCreate$Params } from '../fn/inventory/inventory-stock-ins-import-create';
import { inventoryStockInsList } from '../fn/inventory/inventory-stock-ins-list';
import { InventoryStockInsList$Params } from '../fn/inventory/inventory-stock-ins-list';
import { inventoryStockInsPartialUpdate$FormData } from '../fn/inventory/inventory-stock-ins-partial-update-form-data';
import { InventoryStockInsPartialUpdate$FormData$Params } from '../fn/inventory/inventory-stock-ins-partial-update-form-data';
import { inventoryStockInsPartialUpdate$Json } from '../fn/inventory/inventory-stock-ins-partial-update-json';
import { InventoryStockInsPartialUpdate$Json$Params } from '../fn/inventory/inventory-stock-ins-partial-update-json';
import { inventoryStockInsPartialUpdate$XWwwFormUrlencoded } from '../fn/inventory/inventory-stock-ins-partial-update-x-www-form-urlencoded';
import { InventoryStockInsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-stock-ins-partial-update-x-www-form-urlencoded';
import { inventoryStockInsPostCreate } from '../fn/inventory/inventory-stock-ins-post-create';
import { InventoryStockInsPostCreate$Params } from '../fn/inventory/inventory-stock-ins-post-create';
import { inventoryStockInsRetrieve } from '../fn/inventory/inventory-stock-ins-retrieve';
import { InventoryStockInsRetrieve$Params } from '../fn/inventory/inventory-stock-ins-retrieve';
import { inventoryStockInsReverseCreate$FormData } from '../fn/inventory/inventory-stock-ins-reverse-create-form-data';
import { InventoryStockInsReverseCreate$FormData$Params } from '../fn/inventory/inventory-stock-ins-reverse-create-form-data';
import { inventoryStockInsReverseCreate$Json } from '../fn/inventory/inventory-stock-ins-reverse-create-json';
import { InventoryStockInsReverseCreate$Json$Params } from '../fn/inventory/inventory-stock-ins-reverse-create-json';
import { inventoryStockInsReverseCreate$XWwwFormUrlencoded } from '../fn/inventory/inventory-stock-ins-reverse-create-x-www-form-urlencoded';
import { InventoryStockInsReverseCreate$XWwwFormUrlencoded$Params } from '../fn/inventory/inventory-stock-ins-reverse-create-x-www-form-urlencoded';
import { PaginatedAdjustmentList } from '../models/paginated-adjustment-list';
import { PaginatedStockCountList } from '../models/paginated-stock-count-list';
import { PaginatedStockInList } from '../models/paginated-stock-in-list';
import { PaginatedStockMovementList } from '../models/paginated-stock-movement-list';
import { StockCount } from '../models/stock-count';
import { StockIn } from '../models/stock-in';
import { StockMovement } from '../models/stock-movement';

@Injectable({ providedIn: 'root' })
export class InventoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `inventoryAdjustmentsList()` */
  static readonly InventoryAdjustmentsListPath = '/api/inventory/adjustments/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryAdjustmentsList$Response(params?: InventoryAdjustmentsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedAdjustmentList>> {
    const obs = inventoryAdjustmentsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryAdjustmentsList(params?: InventoryAdjustmentsList$Params, context?: HttpContext): Observable<PaginatedAdjustmentList> {
    const resp = this.inventoryAdjustmentsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedAdjustmentList>): PaginatedAdjustmentList => r.body)
    );
  }

  /** Path part for operation `inventoryAdjustmentsCreate()` */
  static readonly InventoryAdjustmentsCreatePath = '/api/inventory/adjustments/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryAdjustmentsCreate$Json$Response(params: InventoryAdjustmentsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryAdjustmentsCreate$Json(params: InventoryAdjustmentsCreate$Json$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryAdjustmentsCreate$XWwwFormUrlencoded$Response(params: InventoryAdjustmentsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryAdjustmentsCreate$XWwwFormUrlencoded(params: InventoryAdjustmentsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryAdjustmentsCreate$FormData$Response(params: InventoryAdjustmentsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryAdjustmentsCreate$FormData(params: InventoryAdjustmentsCreate$FormData$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /** Path part for operation `inventoryAdjustmentsRetrieve()` */
  static readonly InventoryAdjustmentsRetrievePath = '/api/inventory/adjustments/{id}/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryAdjustmentsRetrieve$Response(params: InventoryAdjustmentsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryAdjustmentsRetrieve(params: InventoryAdjustmentsRetrieve$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /** Path part for operation `inventoryAdjustmentsDestroy()` */
  static readonly InventoryAdjustmentsDestroyPath = '/api/inventory/adjustments/{id}/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsDestroy()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryAdjustmentsDestroy$Response(params: InventoryAdjustmentsDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = inventoryAdjustmentsDestroy(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsDestroy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryAdjustmentsDestroy(params: InventoryAdjustmentsDestroy$Params, context?: HttpContext): Observable<void> {
    const resp = this.inventoryAdjustmentsDestroy$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `inventoryAdjustmentsPartialUpdate()` */
  static readonly InventoryAdjustmentsPartialUpdatePath = '/api/inventory/adjustments/{id}/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryAdjustmentsPartialUpdate$Json$Response(params: InventoryAdjustmentsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryAdjustmentsPartialUpdate$Json(params: InventoryAdjustmentsPartialUpdate$Json$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded$Response(params: InventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded(params: InventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryAdjustmentsPartialUpdate$FormData$Response(params: InventoryAdjustmentsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryAdjustmentsPartialUpdate$FormData(params: InventoryAdjustmentsPartialUpdate$FormData$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /** Path part for operation `inventoryAdjustmentsImportCreate()` */
  static readonly InventoryAdjustmentsImportCreatePath = '/api/inventory/adjustments/{id}/import/';

  /**
   * Check a CSV or Excel file against this draft; with commit=true,
   * add the rows that passed.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsImportCreate()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryAdjustmentsImportCreate$Response(params: InventoryAdjustmentsImportCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportResult>> {
    const obs = inventoryAdjustmentsImportCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Check a CSV or Excel file against this draft; with commit=true,
   * add the rows that passed.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsImportCreate$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryAdjustmentsImportCreate(params: InventoryAdjustmentsImportCreate$Params, context?: HttpContext): Observable<ImportResult> {
    const resp = this.inventoryAdjustmentsImportCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ImportResult>): ImportResult => r.body)
    );
  }

  /** Path part for operation `inventoryAdjustmentsPostCreate()` */
  static readonly InventoryAdjustmentsPostCreatePath = '/api/inventory/adjustments/{id}/post/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsPostCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryAdjustmentsPostCreate$Response(params: InventoryAdjustmentsPostCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsPostCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsPostCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryAdjustmentsPostCreate(params: InventoryAdjustmentsPostCreate$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsPostCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /** Path part for operation `inventoryAdjustmentsReverseCreate()` */
  static readonly InventoryAdjustmentsReverseCreatePath = '/api/inventory/adjustments/{id}/reverse/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsReverseCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryAdjustmentsReverseCreate$Json$Response(params: InventoryAdjustmentsReverseCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsReverseCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsReverseCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryAdjustmentsReverseCreate$Json(params: InventoryAdjustmentsReverseCreate$Json$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsReverseCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsReverseCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryAdjustmentsReverseCreate$XWwwFormUrlencoded$Response(params: InventoryAdjustmentsReverseCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsReverseCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsReverseCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryAdjustmentsReverseCreate$XWwwFormUrlencoded(params: InventoryAdjustmentsReverseCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsReverseCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryAdjustmentsReverseCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryAdjustmentsReverseCreate$FormData$Response(params: InventoryAdjustmentsReverseCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Adjustment>> {
    const obs = inventoryAdjustmentsReverseCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryAdjustmentsReverseCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryAdjustmentsReverseCreate$FormData(params: InventoryAdjustmentsReverseCreate$FormData$Params, context?: HttpContext): Observable<Adjustment> {
    const resp = this.inventoryAdjustmentsReverseCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Adjustment>): Adjustment => r.body)
    );
  }

  /** Path part for operation `inventoryCountsList()` */
  static readonly InventoryCountsListPath = '/api/inventory/counts/';

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryCountsList$Response(params?: InventoryCountsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedStockCountList>> {
    const obs = inventoryCountsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryCountsList(params?: InventoryCountsList$Params, context?: HttpContext): Observable<PaginatedStockCountList> {
    const resp = this.inventoryCountsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedStockCountList>): PaginatedStockCountList => r.body)
    );
  }

  /** Path part for operation `inventoryCountsCreate()` */
  static readonly InventoryCountsCreatePath = '/api/inventory/counts/';

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryCountsCreate$Json$Response(params: InventoryCountsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryCountsCreate$Json(params: InventoryCountsCreate$Json$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryCountsCreate$XWwwFormUrlencoded$Response(params: InventoryCountsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryCountsCreate$XWwwFormUrlencoded(params: InventoryCountsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryCountsCreate$FormData$Response(params: InventoryCountsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryCountsCreate$FormData(params: InventoryCountsCreate$FormData$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /** Path part for operation `inventoryCountsRetrieve()` */
  static readonly InventoryCountsRetrievePath = '/api/inventory/counts/{id}/';

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryCountsRetrieve$Response(params: InventoryCountsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryCountsRetrieve(params: InventoryCountsRetrieve$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /** Path part for operation `inventoryCountsDestroy()` */
  static readonly InventoryCountsDestroyPath = '/api/inventory/counts/{id}/';

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsDestroy()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryCountsDestroy$Response(params: InventoryCountsDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = inventoryCountsDestroy(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsDestroy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryCountsDestroy(params: InventoryCountsDestroy$Params, context?: HttpContext): Observable<void> {
    const resp = this.inventoryCountsDestroy$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `inventoryCountsPartialUpdate()` */
  static readonly InventoryCountsPartialUpdatePath = '/api/inventory/counts/{id}/';

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryCountsPartialUpdate$Json$Response(params: InventoryCountsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryCountsPartialUpdate$Json(params: InventoryCountsPartialUpdate$Json$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryCountsPartialUpdate$XWwwFormUrlencoded$Response(params: InventoryCountsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryCountsPartialUpdate$XWwwFormUrlencoded(params: InventoryCountsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryCountsPartialUpdate$FormData$Response(params: InventoryCountsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryCountsPartialUpdate$FormData(params: InventoryCountsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /** Path part for operation `inventoryCountsPostCreate()` */
  static readonly InventoryCountsPostCreatePath = '/api/inventory/counts/{id}/post/';

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsPostCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryCountsPostCreate$Response(params: InventoryCountsPostCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsPostCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsPostCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryCountsPostCreate(params: InventoryCountsPostCreate$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsPostCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /** Path part for operation `inventoryCountsRecordCreate()` */
  static readonly InventoryCountsRecordCreatePath = '/api/inventory/counts/{id}/record/';

  /**
   * Enter counted quantities: {"lines": [{"line": id, "counted_qty": "5"}]}.
   * A null counted_qty clears the line.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsRecordCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryCountsRecordCreate$Json$Response(params: InventoryCountsRecordCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsRecordCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Enter counted quantities: {"lines": [{"line": id, "counted_qty": "5"}]}.
   * A null counted_qty clears the line.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsRecordCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryCountsRecordCreate$Json(params: InventoryCountsRecordCreate$Json$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsRecordCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /**
   * Enter counted quantities: {"lines": [{"line": id, "counted_qty": "5"}]}.
   * A null counted_qty clears the line.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsRecordCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryCountsRecordCreate$XWwwFormUrlencoded$Response(params: InventoryCountsRecordCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsRecordCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Enter counted quantities: {"lines": [{"line": id, "counted_qty": "5"}]}.
   * A null counted_qty clears the line.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsRecordCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryCountsRecordCreate$XWwwFormUrlencoded(params: InventoryCountsRecordCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsRecordCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /**
   * Enter counted quantities: {"lines": [{"line": id, "counted_qty": "5"}]}.
   * A null counted_qty clears the line.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsRecordCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryCountsRecordCreate$FormData$Response(params: InventoryCountsRecordCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsRecordCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Enter counted quantities: {"lines": [{"line": id, "counted_qty": "5"}]}.
   * A null counted_qty clears the line.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsRecordCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryCountsRecordCreate$FormData(params: InventoryCountsRecordCreate$FormData$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsRecordCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /** Path part for operation `inventoryCountsReverseCreate()` */
  static readonly InventoryCountsReverseCreatePath = '/api/inventory/counts/{id}/reverse/';

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsReverseCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryCountsReverseCreate$Json$Response(params: InventoryCountsReverseCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsReverseCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsReverseCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryCountsReverseCreate$Json(params: InventoryCountsReverseCreate$Json$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsReverseCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsReverseCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryCountsReverseCreate$XWwwFormUrlencoded$Response(params: InventoryCountsReverseCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsReverseCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsReverseCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryCountsReverseCreate$XWwwFormUrlencoded(params: InventoryCountsReverseCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsReverseCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryCountsReverseCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryCountsReverseCreate$FormData$Response(params: InventoryCountsReverseCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<StockCount>> {
    const obs = inventoryCountsReverseCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST starts a count for a category. DELETE on a draft abandons it.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryCountsReverseCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryCountsReverseCreate$FormData(params: InventoryCountsReverseCreate$FormData$Params, context?: HttpContext): Observable<StockCount> {
    const resp = this.inventoryCountsReverseCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockCount>): StockCount => r.body)
    );
  }

  /** Path part for operation `inventoryMovementsList()` */
  static readonly InventoryMovementsListPath = '/api/inventory/movements/';

  /**
   * The ledger. Filter by product for a stock card.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryMovementsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryMovementsList$Response(params?: InventoryMovementsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedStockMovementList>> {
    const obs = inventoryMovementsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * The ledger. Filter by product for a stock card.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryMovementsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryMovementsList(params?: InventoryMovementsList$Params, context?: HttpContext): Observable<PaginatedStockMovementList> {
    const resp = this.inventoryMovementsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedStockMovementList>): PaginatedStockMovementList => r.body)
    );
  }

  /** Path part for operation `inventoryMovementsRetrieve()` */
  static readonly InventoryMovementsRetrievePath = '/api/inventory/movements/{id}/';

  /**
   * The ledger. Filter by product for a stock card.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryMovementsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryMovementsRetrieve$Response(params: InventoryMovementsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<StockMovement>> {
    const obs = inventoryMovementsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * The ledger. Filter by product for a stock card.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryMovementsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryMovementsRetrieve(params: InventoryMovementsRetrieve$Params, context?: HttpContext): Observable<StockMovement> {
    const resp = this.inventoryMovementsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockMovement>): StockMovement => r.body)
    );
  }

  /** Path part for operation `inventoryStockInsList()` */
  static readonly InventoryStockInsListPath = '/api/inventory/stock-ins/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryStockInsList$Response(params?: InventoryStockInsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedStockInList>> {
    const obs = inventoryStockInsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryStockInsList(params?: InventoryStockInsList$Params, context?: HttpContext): Observable<PaginatedStockInList> {
    const resp = this.inventoryStockInsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedStockInList>): PaginatedStockInList => r.body)
    );
  }

  /** Path part for operation `inventoryStockInsCreate()` */
  static readonly InventoryStockInsCreatePath = '/api/inventory/stock-ins/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryStockInsCreate$Json$Response(params: InventoryStockInsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryStockInsCreate$Json(params: InventoryStockInsCreate$Json$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryStockInsCreate$XWwwFormUrlencoded$Response(params: InventoryStockInsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryStockInsCreate$XWwwFormUrlencoded(params: InventoryStockInsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryStockInsCreate$FormData$Response(params: InventoryStockInsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryStockInsCreate$FormData(params: InventoryStockInsCreate$FormData$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /** Path part for operation `inventoryStockInsRetrieve()` */
  static readonly InventoryStockInsRetrievePath = '/api/inventory/stock-ins/{id}/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryStockInsRetrieve$Response(params: InventoryStockInsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryStockInsRetrieve(params: InventoryStockInsRetrieve$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /** Path part for operation `inventoryStockInsDestroy()` */
  static readonly InventoryStockInsDestroyPath = '/api/inventory/stock-ins/{id}/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsDestroy()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryStockInsDestroy$Response(params: InventoryStockInsDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = inventoryStockInsDestroy(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsDestroy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryStockInsDestroy(params: InventoryStockInsDestroy$Params, context?: HttpContext): Observable<void> {
    const resp = this.inventoryStockInsDestroy$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `inventoryStockInsPartialUpdate()` */
  static readonly InventoryStockInsPartialUpdatePath = '/api/inventory/stock-ins/{id}/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryStockInsPartialUpdate$Json$Response(params: InventoryStockInsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryStockInsPartialUpdate$Json(params: InventoryStockInsPartialUpdate$Json$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryStockInsPartialUpdate$XWwwFormUrlencoded$Response(params: InventoryStockInsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryStockInsPartialUpdate$XWwwFormUrlencoded(params: InventoryStockInsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryStockInsPartialUpdate$FormData$Response(params: InventoryStockInsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryStockInsPartialUpdate$FormData(params: InventoryStockInsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /** Path part for operation `inventoryStockInsImportCreate()` */
  static readonly InventoryStockInsImportCreatePath = '/api/inventory/stock-ins/{id}/import/';

  /**
   * Check a CSV or Excel file against this draft; with commit=true,
   * add the rows that passed.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsImportCreate()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryStockInsImportCreate$Response(params: InventoryStockInsImportCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportResult>> {
    const obs = inventoryStockInsImportCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Check a CSV or Excel file against this draft; with commit=true,
   * add the rows that passed.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsImportCreate$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryStockInsImportCreate(params: InventoryStockInsImportCreate$Params, context?: HttpContext): Observable<ImportResult> {
    const resp = this.inventoryStockInsImportCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ImportResult>): ImportResult => r.body)
    );
  }

  /** Path part for operation `inventoryStockInsPostCreate()` */
  static readonly InventoryStockInsPostCreatePath = '/api/inventory/stock-ins/{id}/post/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsPostCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryStockInsPostCreate$Response(params: InventoryStockInsPostCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsPostCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsPostCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inventoryStockInsPostCreate(params: InventoryStockInsPostCreate$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsPostCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /** Path part for operation `inventoryStockInsReverseCreate()` */
  static readonly InventoryStockInsReverseCreatePath = '/api/inventory/stock-ins/{id}/reverse/';

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsReverseCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryStockInsReverseCreate$Json$Response(params: InventoryStockInsReverseCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsReverseCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsReverseCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inventoryStockInsReverseCreate$Json(params: InventoryStockInsReverseCreate$Json$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsReverseCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsReverseCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryStockInsReverseCreate$XWwwFormUrlencoded$Response(params: InventoryStockInsReverseCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsReverseCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsReverseCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  inventoryStockInsReverseCreate$XWwwFormUrlencoded(params: InventoryStockInsReverseCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsReverseCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inventoryStockInsReverseCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryStockInsReverseCreate$FormData$Response(params: InventoryStockInsReverseCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<StockIn>> {
    const obs = inventoryStockInsReverseCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Drafts are created, edited and deleted freely. Posting and reversing
   * are actions; a posted document refuses PATCH and DELETE.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inventoryStockInsReverseCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inventoryStockInsReverseCreate$FormData(params: InventoryStockInsReverseCreate$FormData$Params, context?: HttpContext): Observable<StockIn> {
    const resp = this.inventoryStockInsReverseCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockIn>): StockIn => r.body)
    );
  }

}
