/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Customer } from '../models/customer';
import { CustomerLookup } from '../models/customer-lookup';
import { PaginatedCustomerList } from '../models/paginated-customer-list';
import { PaginatedProductSupplierList } from '../models/paginated-product-supplier-list';
import { PaginatedSupplierList } from '../models/paginated-supplier-list';
import { partnersCustomersCreate$FormData } from '../fn/partners/partners-customers-create-form-data';
import { PartnersCustomersCreate$FormData$Params } from '../fn/partners/partners-customers-create-form-data';
import { partnersCustomersCreate$Json } from '../fn/partners/partners-customers-create-json';
import { PartnersCustomersCreate$Json$Params } from '../fn/partners/partners-customers-create-json';
import { partnersCustomersCreate$XWwwFormUrlencoded } from '../fn/partners/partners-customers-create-x-www-form-urlencoded';
import { PartnersCustomersCreate$XWwwFormUrlencoded$Params } from '../fn/partners/partners-customers-create-x-www-form-urlencoded';
import { partnersCustomersList } from '../fn/partners/partners-customers-list';
import { PartnersCustomersList$Params } from '../fn/partners/partners-customers-list';
import { partnersCustomersLookupList } from '../fn/partners/partners-customers-lookup-list';
import { PartnersCustomersLookupList$Params } from '../fn/partners/partners-customers-lookup-list';
import { partnersCustomersPartialUpdate$FormData } from '../fn/partners/partners-customers-partial-update-form-data';
import { PartnersCustomersPartialUpdate$FormData$Params } from '../fn/partners/partners-customers-partial-update-form-data';
import { partnersCustomersPartialUpdate$Json } from '../fn/partners/partners-customers-partial-update-json';
import { PartnersCustomersPartialUpdate$Json$Params } from '../fn/partners/partners-customers-partial-update-json';
import { partnersCustomersPartialUpdate$XWwwFormUrlencoded } from '../fn/partners/partners-customers-partial-update-x-www-form-urlencoded';
import { PartnersCustomersPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/partners/partners-customers-partial-update-x-www-form-urlencoded';
import { partnersCustomersRetrieve } from '../fn/partners/partners-customers-retrieve';
import { PartnersCustomersRetrieve$Params } from '../fn/partners/partners-customers-retrieve';
import { partnersProductSuppliersCreate$FormData } from '../fn/partners/partners-product-suppliers-create-form-data';
import { PartnersProductSuppliersCreate$FormData$Params } from '../fn/partners/partners-product-suppliers-create-form-data';
import { partnersProductSuppliersCreate$Json } from '../fn/partners/partners-product-suppliers-create-json';
import { PartnersProductSuppliersCreate$Json$Params } from '../fn/partners/partners-product-suppliers-create-json';
import { partnersProductSuppliersCreate$XWwwFormUrlencoded } from '../fn/partners/partners-product-suppliers-create-x-www-form-urlencoded';
import { PartnersProductSuppliersCreate$XWwwFormUrlencoded$Params } from '../fn/partners/partners-product-suppliers-create-x-www-form-urlencoded';
import { partnersProductSuppliersDestroy } from '../fn/partners/partners-product-suppliers-destroy';
import { PartnersProductSuppliersDestroy$Params } from '../fn/partners/partners-product-suppliers-destroy';
import { partnersProductSuppliersList } from '../fn/partners/partners-product-suppliers-list';
import { PartnersProductSuppliersList$Params } from '../fn/partners/partners-product-suppliers-list';
import { partnersProductSuppliersPartialUpdate$FormData } from '../fn/partners/partners-product-suppliers-partial-update-form-data';
import { PartnersProductSuppliersPartialUpdate$FormData$Params } from '../fn/partners/partners-product-suppliers-partial-update-form-data';
import { partnersProductSuppliersPartialUpdate$Json } from '../fn/partners/partners-product-suppliers-partial-update-json';
import { PartnersProductSuppliersPartialUpdate$Json$Params } from '../fn/partners/partners-product-suppliers-partial-update-json';
import { partnersProductSuppliersPartialUpdate$XWwwFormUrlencoded } from '../fn/partners/partners-product-suppliers-partial-update-x-www-form-urlencoded';
import { PartnersProductSuppliersPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/partners/partners-product-suppliers-partial-update-x-www-form-urlencoded';
import { partnersProductSuppliersRetrieve } from '../fn/partners/partners-product-suppliers-retrieve';
import { PartnersProductSuppliersRetrieve$Params } from '../fn/partners/partners-product-suppliers-retrieve';
import { partnersSuppliersCreate$FormData } from '../fn/partners/partners-suppliers-create-form-data';
import { PartnersSuppliersCreate$FormData$Params } from '../fn/partners/partners-suppliers-create-form-data';
import { partnersSuppliersCreate$Json } from '../fn/partners/partners-suppliers-create-json';
import { PartnersSuppliersCreate$Json$Params } from '../fn/partners/partners-suppliers-create-json';
import { partnersSuppliersCreate$XWwwFormUrlencoded } from '../fn/partners/partners-suppliers-create-x-www-form-urlencoded';
import { PartnersSuppliersCreate$XWwwFormUrlencoded$Params } from '../fn/partners/partners-suppliers-create-x-www-form-urlencoded';
import { partnersSuppliersList } from '../fn/partners/partners-suppliers-list';
import { PartnersSuppliersList$Params } from '../fn/partners/partners-suppliers-list';
import { partnersSuppliersPartialUpdate$FormData } from '../fn/partners/partners-suppliers-partial-update-form-data';
import { PartnersSuppliersPartialUpdate$FormData$Params } from '../fn/partners/partners-suppliers-partial-update-form-data';
import { partnersSuppliersPartialUpdate$Json } from '../fn/partners/partners-suppliers-partial-update-json';
import { PartnersSuppliersPartialUpdate$Json$Params } from '../fn/partners/partners-suppliers-partial-update-json';
import { partnersSuppliersPartialUpdate$XWwwFormUrlencoded } from '../fn/partners/partners-suppliers-partial-update-x-www-form-urlencoded';
import { PartnersSuppliersPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/partners/partners-suppliers-partial-update-x-www-form-urlencoded';
import { partnersSuppliersRetrieve } from '../fn/partners/partners-suppliers-retrieve';
import { PartnersSuppliersRetrieve$Params } from '../fn/partners/partners-suppliers-retrieve';
import { ProductSupplier } from '../models/product-supplier';
import { Supplier } from '../models/supplier';

@Injectable({ providedIn: 'root' })
export class PartnersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `partnersCustomersList()` */
  static readonly PartnersCustomersListPath = '/api/partners/customers/';

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersList()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersCustomersList$Response(params?: PartnersCustomersList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedCustomerList>> {
    const obs = partnersCustomersList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersCustomersList(params?: PartnersCustomersList$Params, context?: HttpContext): Observable<PaginatedCustomerList> {
    const resp = this.partnersCustomersList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedCustomerList>): PaginatedCustomerList => r.body)
    );
  }

  /** Path part for operation `partnersCustomersCreate()` */
  static readonly PartnersCustomersCreatePath = '/api/partners/customers/';

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersCustomersCreate$Json$Response(params: PartnersCustomersCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Customer>> {
    const obs = partnersCustomersCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersCustomersCreate$Json(params: PartnersCustomersCreate$Json$Params, context?: HttpContext): Observable<Customer> {
    const resp = this.partnersCustomersCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Customer>): Customer => r.body)
    );
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersCustomersCreate$XWwwFormUrlencoded$Response(params: PartnersCustomersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Customer>> {
    const obs = partnersCustomersCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersCustomersCreate$XWwwFormUrlencoded(params: PartnersCustomersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Customer> {
    const resp = this.partnersCustomersCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Customer>): Customer => r.body)
    );
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersCustomersCreate$FormData$Response(params: PartnersCustomersCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Customer>> {
    const obs = partnersCustomersCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersCustomersCreate$FormData(params: PartnersCustomersCreate$FormData$Params, context?: HttpContext): Observable<Customer> {
    const resp = this.partnersCustomersCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Customer>): Customer => r.body)
    );
  }

  /** Path part for operation `partnersCustomersRetrieve()` */
  static readonly PartnersCustomersRetrievePath = '/api/partners/customers/{id}/';

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersCustomersRetrieve$Response(params: PartnersCustomersRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Customer>> {
    const obs = partnersCustomersRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersCustomersRetrieve(params: PartnersCustomersRetrieve$Params, context?: HttpContext): Observable<Customer> {
    const resp = this.partnersCustomersRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Customer>): Customer => r.body)
    );
  }

  /** Path part for operation `partnersCustomersPartialUpdate()` */
  static readonly PartnersCustomersPartialUpdatePath = '/api/partners/customers/{id}/';

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersCustomersPartialUpdate$Json$Response(params: PartnersCustomersPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Customer>> {
    const obs = partnersCustomersPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersCustomersPartialUpdate$Json(params: PartnersCustomersPartialUpdate$Json$Params, context?: HttpContext): Observable<Customer> {
    const resp = this.partnersCustomersPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Customer>): Customer => r.body)
    );
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersCustomersPartialUpdate$XWwwFormUrlencoded$Response(params: PartnersCustomersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Customer>> {
    const obs = partnersCustomersPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersCustomersPartialUpdate$XWwwFormUrlencoded(params: PartnersCustomersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Customer> {
    const resp = this.partnersCustomersPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Customer>): Customer => r.body)
    );
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersCustomersPartialUpdate$FormData$Response(params: PartnersCustomersPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Customer>> {
    const obs = partnersCustomersPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: customers have sales against them, so they are deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersCustomersPartialUpdate$FormData(params: PartnersCustomersPartialUpdate$FormData$Params, context?: HttpContext): Observable<Customer> {
    const resp = this.partnersCustomersPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Customer>): Customer => r.body)
    );
  }

  /** Path part for operation `partnersCustomersLookupList()` */
  static readonly PartnersCustomersLookupListPath = '/api/partners/customers/lookup/';

  /**
   * Small payload for the till. Active only, walk-in first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersCustomersLookupList()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersCustomersLookupList$Response(params?: PartnersCustomersLookupList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerLookup>>> {
    const obs = partnersCustomersLookupList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Small payload for the till. Active only, walk-in first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersCustomersLookupList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersCustomersLookupList(params?: PartnersCustomersLookupList$Params, context?: HttpContext): Observable<Array<CustomerLookup>> {
    const resp = this.partnersCustomersLookupList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<CustomerLookup>>): Array<CustomerLookup> => r.body)
    );
  }

  /** Path part for operation `partnersProductSuppliersList()` */
  static readonly PartnersProductSuppliersListPath = '/api/partners/product-suppliers/';

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersList()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersProductSuppliersList$Response(params?: PartnersProductSuppliersList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedProductSupplierList>> {
    const obs = partnersProductSuppliersList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersProductSuppliersList(params?: PartnersProductSuppliersList$Params, context?: HttpContext): Observable<PaginatedProductSupplierList> {
    const resp = this.partnersProductSuppliersList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedProductSupplierList>): PaginatedProductSupplierList => r.body)
    );
  }

  /** Path part for operation `partnersProductSuppliersCreate()` */
  static readonly PartnersProductSuppliersCreatePath = '/api/partners/product-suppliers/';

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersProductSuppliersCreate$Json$Response(params: PartnersProductSuppliersCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
    const obs = partnersProductSuppliersCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersProductSuppliersCreate$Json(params: PartnersProductSuppliersCreate$Json$Params, context?: HttpContext): Observable<ProductSupplier> {
    const resp = this.partnersProductSuppliersCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProductSupplier>): ProductSupplier => r.body)
    );
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersProductSuppliersCreate$XWwwFormUrlencoded$Response(params: PartnersProductSuppliersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
    const obs = partnersProductSuppliersCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersProductSuppliersCreate$XWwwFormUrlencoded(params: PartnersProductSuppliersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<ProductSupplier> {
    const resp = this.partnersProductSuppliersCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProductSupplier>): ProductSupplier => r.body)
    );
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersProductSuppliersCreate$FormData$Response(params: PartnersProductSuppliersCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
    const obs = partnersProductSuppliersCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersProductSuppliersCreate$FormData(params: PartnersProductSuppliersCreate$FormData$Params, context?: HttpContext): Observable<ProductSupplier> {
    const resp = this.partnersProductSuppliersCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProductSupplier>): ProductSupplier => r.body)
    );
  }

  /** Path part for operation `partnersProductSuppliersRetrieve()` */
  static readonly PartnersProductSuppliersRetrievePath = '/api/partners/product-suppliers/{id}/';

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersProductSuppliersRetrieve$Response(params: PartnersProductSuppliersRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
    const obs = partnersProductSuppliersRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersProductSuppliersRetrieve(params: PartnersProductSuppliersRetrieve$Params, context?: HttpContext): Observable<ProductSupplier> {
    const resp = this.partnersProductSuppliersRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProductSupplier>): ProductSupplier => r.body)
    );
  }

  /** Path part for operation `partnersProductSuppliersDestroy()` */
  static readonly PartnersProductSuppliersDestroyPath = '/api/partners/product-suppliers/{id}/';

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersDestroy()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersProductSuppliersDestroy$Response(params: PartnersProductSuppliersDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = partnersProductSuppliersDestroy(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersDestroy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersProductSuppliersDestroy(params: PartnersProductSuppliersDestroy$Params, context?: HttpContext): Observable<void> {
    const resp = this.partnersProductSuppliersDestroy$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `partnersProductSuppliersPartialUpdate()` */
  static readonly PartnersProductSuppliersPartialUpdatePath = '/api/partners/product-suppliers/{id}/';

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersProductSuppliersPartialUpdate$Json$Response(params: PartnersProductSuppliersPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
    const obs = partnersProductSuppliersPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersProductSuppliersPartialUpdate$Json(params: PartnersProductSuppliersPartialUpdate$Json$Params, context?: HttpContext): Observable<ProductSupplier> {
    const resp = this.partnersProductSuppliersPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProductSupplier>): ProductSupplier => r.body)
    );
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersProductSuppliersPartialUpdate$XWwwFormUrlencoded$Response(params: PartnersProductSuppliersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
    const obs = partnersProductSuppliersPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersProductSuppliersPartialUpdate$XWwwFormUrlencoded(params: PartnersProductSuppliersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<ProductSupplier> {
    const resp = this.partnersProductSuppliersPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProductSupplier>): ProductSupplier => r.body)
    );
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersProductSuppliersPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersProductSuppliersPartialUpdate$FormData$Response(params: PartnersProductSuppliersPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductSupplier>> {
    const obs = partnersProductSuppliersPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Links may be deleted — they carry no history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersProductSuppliersPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersProductSuppliersPartialUpdate$FormData(params: PartnersProductSuppliersPartialUpdate$FormData$Params, context?: HttpContext): Observable<ProductSupplier> {
    const resp = this.partnersProductSuppliersPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProductSupplier>): ProductSupplier => r.body)
    );
  }

  /** Path part for operation `partnersSuppliersList()` */
  static readonly PartnersSuppliersListPath = '/api/partners/suppliers/';

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersSuppliersList()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersSuppliersList$Response(params?: PartnersSuppliersList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedSupplierList>> {
    const obs = partnersSuppliersList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersSuppliersList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersSuppliersList(params?: PartnersSuppliersList$Params, context?: HttpContext): Observable<PaginatedSupplierList> {
    const resp = this.partnersSuppliersList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedSupplierList>): PaginatedSupplierList => r.body)
    );
  }

  /** Path part for operation `partnersSuppliersCreate()` */
  static readonly PartnersSuppliersCreatePath = '/api/partners/suppliers/';

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersSuppliersCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersSuppliersCreate$Json$Response(params: PartnersSuppliersCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
    const obs = partnersSuppliersCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersSuppliersCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersSuppliersCreate$Json(params: PartnersSuppliersCreate$Json$Params, context?: HttpContext): Observable<Supplier> {
    const resp = this.partnersSuppliersCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Supplier>): Supplier => r.body)
    );
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersSuppliersCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersSuppliersCreate$XWwwFormUrlencoded$Response(params: PartnersSuppliersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
    const obs = partnersSuppliersCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersSuppliersCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersSuppliersCreate$XWwwFormUrlencoded(params: PartnersSuppliersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Supplier> {
    const resp = this.partnersSuppliersCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Supplier>): Supplier => r.body)
    );
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersSuppliersCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersSuppliersCreate$FormData$Response(params: PartnersSuppliersCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
    const obs = partnersSuppliersCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersSuppliersCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersSuppliersCreate$FormData(params: PartnersSuppliersCreate$FormData$Params, context?: HttpContext): Observable<Supplier> {
    const resp = this.partnersSuppliersCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Supplier>): Supplier => r.body)
    );
  }

  /** Path part for operation `partnersSuppliersRetrieve()` */
  static readonly PartnersSuppliersRetrievePath = '/api/partners/suppliers/{id}/';

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersSuppliersRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersSuppliersRetrieve$Response(params: PartnersSuppliersRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
    const obs = partnersSuppliersRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersSuppliersRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partnersSuppliersRetrieve(params: PartnersSuppliersRetrieve$Params, context?: HttpContext): Observable<Supplier> {
    const resp = this.partnersSuppliersRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Supplier>): Supplier => r.body)
    );
  }

  /** Path part for operation `partnersSuppliersPartialUpdate()` */
  static readonly PartnersSuppliersPartialUpdatePath = '/api/partners/suppliers/{id}/';

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersSuppliersPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersSuppliersPartialUpdate$Json$Response(params: PartnersSuppliersPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
    const obs = partnersSuppliersPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersSuppliersPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partnersSuppliersPartialUpdate$Json(params: PartnersSuppliersPartialUpdate$Json$Params, context?: HttpContext): Observable<Supplier> {
    const resp = this.partnersSuppliersPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Supplier>): Supplier => r.body)
    );
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersSuppliersPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersSuppliersPartialUpdate$XWwwFormUrlencoded$Response(params: PartnersSuppliersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
    const obs = partnersSuppliersPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersSuppliersPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  partnersSuppliersPartialUpdate$XWwwFormUrlencoded(params: PartnersSuppliersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Supplier> {
    const resp = this.partnersSuppliersPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Supplier>): Supplier => r.body)
    );
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partnersSuppliersPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersSuppliersPartialUpdate$FormData$Response(params: PartnersSuppliersPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Supplier>> {
    const obs = partnersSuppliersPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * No delete: past stock-ins keep their supplier, so it is deactivated.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partnersSuppliersPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  partnersSuppliersPartialUpdate$FormData(params: PartnersSuppliersPartialUpdate$FormData$Params, context?: HttpContext): Observable<Supplier> {
    const resp = this.partnersSuppliersPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Supplier>): Supplier => r.body)
    );
  }

}
