/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DailySales } from '../models/daily-sales';
import { Dashboard } from '../models/dashboard';
import { Receivables } from '../models/receivables';
import { reportsDailySalesRetrieve } from '../fn/reports/reports-daily-sales-retrieve';
import { ReportsDailySalesRetrieve$Params } from '../fn/reports/reports-daily-sales-retrieve';
import { reportsDashboardRetrieve } from '../fn/reports/reports-dashboard-retrieve';
import { ReportsDashboardRetrieve$Params } from '../fn/reports/reports-dashboard-retrieve';
import { reportsReceivablesRetrieve } from '../fn/reports/reports-receivables-retrieve';
import { ReportsReceivablesRetrieve$Params } from '../fn/reports/reports-receivables-retrieve';
import { reportsStockOnHandRetrieve } from '../fn/reports/reports-stock-on-hand-retrieve';
import { ReportsStockOnHandRetrieve$Params } from '../fn/reports/reports-stock-on-hand-retrieve';
import { StockOnHand } from '../models/stock-on-hand';

@Injectable({ providedIn: 'root' })
export class ReportsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `reportsDailySalesRetrieve()` */
  static readonly ReportsDailySalesRetrievePath = '/api/reports/daily-sales/';

  /**
   * Completed sales by day, by seller and by tender, this month unless
   * dates are given. A Seller's report is always their own.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsDailySalesRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsDailySalesRetrieve$Response(params?: ReportsDailySalesRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<DailySales>> {
    const obs = reportsDailySalesRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Completed sales by day, by seller and by tender, this month unless
   * dates are given. A Seller's report is always their own.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsDailySalesRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsDailySalesRetrieve(params?: ReportsDailySalesRetrieve$Params, context?: HttpContext): Observable<DailySales> {
    const resp = this.reportsDailySalesRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<DailySales>): DailySales => r.body)
    );
  }

  /** Path part for operation `reportsDashboardRetrieve()` */
  static readonly ReportsDashboardRetrievePath = '/api/reports/dashboard/';

  /**
   * Today at a glance for whoever is signed in. A part they may not see
   * is null; a Seller's sales are their own.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsDashboardRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsDashboardRetrieve$Response(params?: ReportsDashboardRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Dashboard>> {
    const obs = reportsDashboardRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Today at a glance for whoever is signed in. A part they may not see
   * is null; a Seller's sales are their own.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsDashboardRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsDashboardRetrieve(params?: ReportsDashboardRetrieve$Params, context?: HttpContext): Observable<Dashboard> {
    const resp = this.reportsDashboardRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Dashboard>): Dashboard => r.body)
    );
  }

  /** Path part for operation `reportsReceivablesRetrieve()` */
  static readonly ReportsReceivablesRetrievePath = '/api/reports/receivables/';

  /**
   * What store customers owe, aged by the days since each invoice, as at
   * today. A customer's open invoices: /api/sales/customers/{id}/account/.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsReceivablesRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsReceivablesRetrieve$Response(params?: ReportsReceivablesRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Receivables>> {
    const obs = reportsReceivablesRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * What store customers owe, aged by the days since each invoice, as at
   * today. A customer's open invoices: /api/sales/customers/{id}/account/.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsReceivablesRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsReceivablesRetrieve(params?: ReportsReceivablesRetrieve$Params, context?: HttpContext): Observable<Receivables> {
    const resp = this.reportsReceivablesRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Receivables>): Receivables => r.body)
    );
  }

  /** Path part for operation `reportsStockOnHandRetrieve()` */
  static readonly ReportsStockOnHandRetrievePath = '/api/reports/stock-on-hand/';

  /**
   * What is on the shelf and its value at average cost, as at today. The
   * summary covers all stock; the rows are those the filters keep.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsStockOnHandRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsStockOnHandRetrieve$Response(params?: ReportsStockOnHandRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<StockOnHand>> {
    const obs = reportsStockOnHandRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * What is on the shelf and its value at average cost, as at today. The
   * summary covers all stock; the rows are those the filters keep.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsStockOnHandRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsStockOnHandRetrieve(params?: ReportsStockOnHandRetrieve$Params, context?: HttpContext): Observable<StockOnHand> {
    const resp = this.reportsStockOnHandRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockOnHand>): StockOnHand => r.body)
    );
  }

}
