/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CustomerAccount } from '../models/customer-account';
import { CustomerPayment } from '../models/customer-payment';
import { Invoice } from '../models/invoice';
import { PaginatedCustomerPaymentList } from '../models/paginated-customer-payment-list';
import { PaginatedInvoiceList } from '../models/paginated-invoice-list';
import { PaginatedQuotationList } from '../models/paginated-quotation-list';
import { PaginatedSalesReturnList } from '../models/paginated-sales-return-list';
import { Quotation } from '../models/quotation';
import { salesCustomersAccountRetrieve } from '../fn/sales/sales-customers-account-retrieve';
import { SalesCustomersAccountRetrieve$Params } from '../fn/sales/sales-customers-account-retrieve';
import { salesInvoicesCompleteCreate$FormData } from '../fn/sales/sales-invoices-complete-create-form-data';
import { SalesInvoicesCompleteCreate$FormData$Params } from '../fn/sales/sales-invoices-complete-create-form-data';
import { salesInvoicesCompleteCreate$Json } from '../fn/sales/sales-invoices-complete-create-json';
import { SalesInvoicesCompleteCreate$Json$Params } from '../fn/sales/sales-invoices-complete-create-json';
import { salesInvoicesCompleteCreate$XWwwFormUrlencoded } from '../fn/sales/sales-invoices-complete-create-x-www-form-urlencoded';
import { SalesInvoicesCompleteCreate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-invoices-complete-create-x-www-form-urlencoded';
import { salesInvoicesCreate$FormData } from '../fn/sales/sales-invoices-create-form-data';
import { SalesInvoicesCreate$FormData$Params } from '../fn/sales/sales-invoices-create-form-data';
import { salesInvoicesCreate$Json } from '../fn/sales/sales-invoices-create-json';
import { SalesInvoicesCreate$Json$Params } from '../fn/sales/sales-invoices-create-json';
import { salesInvoicesCreate$XWwwFormUrlencoded } from '../fn/sales/sales-invoices-create-x-www-form-urlencoded';
import { SalesInvoicesCreate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-invoices-create-x-www-form-urlencoded';
import { salesInvoicesDestroy } from '../fn/sales/sales-invoices-destroy';
import { SalesInvoicesDestroy$Params } from '../fn/sales/sales-invoices-destroy';
import { salesInvoicesList } from '../fn/sales/sales-invoices-list';
import { SalesInvoicesList$Params } from '../fn/sales/sales-invoices-list';
import { salesInvoicesPartialUpdate$FormData } from '../fn/sales/sales-invoices-partial-update-form-data';
import { SalesInvoicesPartialUpdate$FormData$Params } from '../fn/sales/sales-invoices-partial-update-form-data';
import { salesInvoicesPartialUpdate$Json } from '../fn/sales/sales-invoices-partial-update-json';
import { SalesInvoicesPartialUpdate$Json$Params } from '../fn/sales/sales-invoices-partial-update-json';
import { salesInvoicesPartialUpdate$XWwwFormUrlencoded } from '../fn/sales/sales-invoices-partial-update-x-www-form-urlencoded';
import { SalesInvoicesPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-invoices-partial-update-x-www-form-urlencoded';
import { salesInvoicesRetrieve } from '../fn/sales/sales-invoices-retrieve';
import { SalesInvoicesRetrieve$Params } from '../fn/sales/sales-invoices-retrieve';
import { salesInvoicesVoidCreate$FormData } from '../fn/sales/sales-invoices-void-create-form-data';
import { SalesInvoicesVoidCreate$FormData$Params } from '../fn/sales/sales-invoices-void-create-form-data';
import { salesInvoicesVoidCreate$Json } from '../fn/sales/sales-invoices-void-create-json';
import { SalesInvoicesVoidCreate$Json$Params } from '../fn/sales/sales-invoices-void-create-json';
import { salesInvoicesVoidCreate$XWwwFormUrlencoded } from '../fn/sales/sales-invoices-void-create-x-www-form-urlencoded';
import { SalesInvoicesVoidCreate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-invoices-void-create-x-www-form-urlencoded';
import { salesPaymentsCreate$FormData } from '../fn/sales/sales-payments-create-form-data';
import { SalesPaymentsCreate$FormData$Params } from '../fn/sales/sales-payments-create-form-data';
import { salesPaymentsCreate$Json } from '../fn/sales/sales-payments-create-json';
import { SalesPaymentsCreate$Json$Params } from '../fn/sales/sales-payments-create-json';
import { salesPaymentsCreate$XWwwFormUrlencoded } from '../fn/sales/sales-payments-create-x-www-form-urlencoded';
import { SalesPaymentsCreate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-payments-create-x-www-form-urlencoded';
import { salesPaymentsList } from '../fn/sales/sales-payments-list';
import { SalesPaymentsList$Params } from '../fn/sales/sales-payments-list';
import { salesPaymentsRetrieve } from '../fn/sales/sales-payments-retrieve';
import { SalesPaymentsRetrieve$Params } from '../fn/sales/sales-payments-retrieve';
import { salesPaymentsVoidCreate$FormData } from '../fn/sales/sales-payments-void-create-form-data';
import { SalesPaymentsVoidCreate$FormData$Params } from '../fn/sales/sales-payments-void-create-form-data';
import { salesPaymentsVoidCreate$Json } from '../fn/sales/sales-payments-void-create-json';
import { SalesPaymentsVoidCreate$Json$Params } from '../fn/sales/sales-payments-void-create-json';
import { salesPaymentsVoidCreate$XWwwFormUrlencoded } from '../fn/sales/sales-payments-void-create-x-www-form-urlencoded';
import { SalesPaymentsVoidCreate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-payments-void-create-x-www-form-urlencoded';
import { salesQuotationsAcceptCreate } from '../fn/sales/sales-quotations-accept-create';
import { SalesQuotationsAcceptCreate$Params } from '../fn/sales/sales-quotations-accept-create';
import { salesQuotationsCreate$FormData } from '../fn/sales/sales-quotations-create-form-data';
import { SalesQuotationsCreate$FormData$Params } from '../fn/sales/sales-quotations-create-form-data';
import { salesQuotationsCreate$Json } from '../fn/sales/sales-quotations-create-json';
import { SalesQuotationsCreate$Json$Params } from '../fn/sales/sales-quotations-create-json';
import { salesQuotationsCreate$XWwwFormUrlencoded } from '../fn/sales/sales-quotations-create-x-www-form-urlencoded';
import { SalesQuotationsCreate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-quotations-create-x-www-form-urlencoded';
import { salesQuotationsDestroy } from '../fn/sales/sales-quotations-destroy';
import { SalesQuotationsDestroy$Params } from '../fn/sales/sales-quotations-destroy';
import { salesQuotationsList } from '../fn/sales/sales-quotations-list';
import { SalesQuotationsList$Params } from '../fn/sales/sales-quotations-list';
import { salesQuotationsPartialUpdate$FormData } from '../fn/sales/sales-quotations-partial-update-form-data';
import { SalesQuotationsPartialUpdate$FormData$Params } from '../fn/sales/sales-quotations-partial-update-form-data';
import { salesQuotationsPartialUpdate$Json } from '../fn/sales/sales-quotations-partial-update-json';
import { SalesQuotationsPartialUpdate$Json$Params } from '../fn/sales/sales-quotations-partial-update-json';
import { salesQuotationsPartialUpdate$XWwwFormUrlencoded } from '../fn/sales/sales-quotations-partial-update-x-www-form-urlencoded';
import { SalesQuotationsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-quotations-partial-update-x-www-form-urlencoded';
import { salesQuotationsRejectCreate$FormData } from '../fn/sales/sales-quotations-reject-create-form-data';
import { SalesQuotationsRejectCreate$FormData$Params } from '../fn/sales/sales-quotations-reject-create-form-data';
import { salesQuotationsRejectCreate$Json } from '../fn/sales/sales-quotations-reject-create-json';
import { SalesQuotationsRejectCreate$Json$Params } from '../fn/sales/sales-quotations-reject-create-json';
import { salesQuotationsRejectCreate$XWwwFormUrlencoded } from '../fn/sales/sales-quotations-reject-create-x-www-form-urlencoded';
import { SalesQuotationsRejectCreate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-quotations-reject-create-x-www-form-urlencoded';
import { salesQuotationsRetrieve } from '../fn/sales/sales-quotations-retrieve';
import { SalesQuotationsRetrieve$Params } from '../fn/sales/sales-quotations-retrieve';
import { salesQuotationsSendCreate } from '../fn/sales/sales-quotations-send-create';
import { SalesQuotationsSendCreate$Params } from '../fn/sales/sales-quotations-send-create';
import { SalesReturn } from '../models/sales-return';
import { salesReturnsCreate$FormData } from '../fn/sales/sales-returns-create-form-data';
import { SalesReturnsCreate$FormData$Params } from '../fn/sales/sales-returns-create-form-data';
import { salesReturnsCreate$Json } from '../fn/sales/sales-returns-create-json';
import { SalesReturnsCreate$Json$Params } from '../fn/sales/sales-returns-create-json';
import { salesReturnsCreate$XWwwFormUrlencoded } from '../fn/sales/sales-returns-create-x-www-form-urlencoded';
import { SalesReturnsCreate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-returns-create-x-www-form-urlencoded';
import { salesReturnsDestroy } from '../fn/sales/sales-returns-destroy';
import { SalesReturnsDestroy$Params } from '../fn/sales/sales-returns-destroy';
import { salesReturnsList } from '../fn/sales/sales-returns-list';
import { SalesReturnsList$Params } from '../fn/sales/sales-returns-list';
import { salesReturnsPartialUpdate$FormData } from '../fn/sales/sales-returns-partial-update-form-data';
import { SalesReturnsPartialUpdate$FormData$Params } from '../fn/sales/sales-returns-partial-update-form-data';
import { salesReturnsPartialUpdate$Json } from '../fn/sales/sales-returns-partial-update-json';
import { SalesReturnsPartialUpdate$Json$Params } from '../fn/sales/sales-returns-partial-update-json';
import { salesReturnsPartialUpdate$XWwwFormUrlencoded } from '../fn/sales/sales-returns-partial-update-x-www-form-urlencoded';
import { SalesReturnsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/sales/sales-returns-partial-update-x-www-form-urlencoded';
import { salesReturnsPostCreate } from '../fn/sales/sales-returns-post-create';
import { SalesReturnsPostCreate$Params } from '../fn/sales/sales-returns-post-create';
import { salesReturnsRetrieve } from '../fn/sales/sales-returns-retrieve';
import { SalesReturnsRetrieve$Params } from '../fn/sales/sales-returns-retrieve';

@Injectable({ providedIn: 'root' })
export class SalesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `salesCustomersAccountRetrieve()` */
  static readonly SalesCustomersAccountRetrievePath = '/api/sales/customers/{id}/account/';

  /**
   * What a customer owes, their room left, and the invoices still open —
   * oldest first, the order a payment is applied in.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesCustomersAccountRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesCustomersAccountRetrieve$Response(params: SalesCustomersAccountRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerAccount>> {
    const obs = salesCustomersAccountRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * What a customer owes, their room left, and the invoices still open —
   * oldest first, the order a payment is applied in.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesCustomersAccountRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesCustomersAccountRetrieve(params: SalesCustomersAccountRetrieve$Params, context?: HttpContext): Observable<CustomerAccount> {
    const resp = this.salesCustomersAccountRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CustomerAccount>): CustomerAccount => r.body)
    );
  }

  /** Path part for operation `salesInvoicesList()` */
  static readonly SalesInvoicesListPath = '/api/sales/invoices/';

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesList()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesInvoicesList$Response(params?: SalesInvoicesList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedInvoiceList>> {
    const obs = salesInvoicesList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesInvoicesList(params?: SalesInvoicesList$Params, context?: HttpContext): Observable<PaginatedInvoiceList> {
    const resp = this.salesInvoicesList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedInvoiceList>): PaginatedInvoiceList => r.body)
    );
  }

  /** Path part for operation `salesInvoicesCreate()` */
  static readonly SalesInvoicesCreatePath = '/api/sales/invoices/';

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesInvoicesCreate$Json$Response(params: SalesInvoicesCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesInvoicesCreate$Json(params: SalesInvoicesCreate$Json$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesInvoicesCreate$XWwwFormUrlencoded$Response(params: SalesInvoicesCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesInvoicesCreate$XWwwFormUrlencoded(params: SalesInvoicesCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesInvoicesCreate$FormData$Response(params: SalesInvoicesCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesInvoicesCreate$FormData(params: SalesInvoicesCreate$FormData$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /** Path part for operation `salesInvoicesRetrieve()` */
  static readonly SalesInvoicesRetrievePath = '/api/sales/invoices/{id}/';

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesInvoicesRetrieve$Response(params: SalesInvoicesRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesInvoicesRetrieve(params: SalesInvoicesRetrieve$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /** Path part for operation `salesInvoicesDestroy()` */
  static readonly SalesInvoicesDestroyPath = '/api/sales/invoices/{id}/';

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesDestroy()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesInvoicesDestroy$Response(params: SalesInvoicesDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = salesInvoicesDestroy(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesDestroy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesInvoicesDestroy(params: SalesInvoicesDestroy$Params, context?: HttpContext): Observable<void> {
    const resp = this.salesInvoicesDestroy$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `salesInvoicesPartialUpdate()` */
  static readonly SalesInvoicesPartialUpdatePath = '/api/sales/invoices/{id}/';

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesInvoicesPartialUpdate$Json$Response(params: SalesInvoicesPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesInvoicesPartialUpdate$Json(params: SalesInvoicesPartialUpdate$Json$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesInvoicesPartialUpdate$XWwwFormUrlencoded$Response(params: SalesInvoicesPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesInvoicesPartialUpdate$XWwwFormUrlencoded(params: SalesInvoicesPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesInvoicesPartialUpdate$FormData$Response(params: SalesInvoicesPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesInvoicesPartialUpdate$FormData(params: SalesInvoicesPartialUpdate$FormData$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /** Path part for operation `salesInvoicesCompleteCreate()` */
  static readonly SalesInvoicesCompleteCreatePath = '/api/sales/invoices/{id}/complete/';

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesCompleteCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesInvoicesCompleteCreate$Json$Response(params: SalesInvoicesCompleteCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesCompleteCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesCompleteCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesInvoicesCompleteCreate$Json(params: SalesInvoicesCompleteCreate$Json$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesCompleteCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesCompleteCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesInvoicesCompleteCreate$XWwwFormUrlencoded$Response(params: SalesInvoicesCompleteCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesCompleteCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesCompleteCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesInvoicesCompleteCreate$XWwwFormUrlencoded(params: SalesInvoicesCompleteCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesCompleteCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesCompleteCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesInvoicesCompleteCreate$FormData$Response(params: SalesInvoicesCompleteCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesCompleteCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesCompleteCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesInvoicesCompleteCreate$FormData(params: SalesInvoicesCompleteCreate$FormData$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesCompleteCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /** Path part for operation `salesInvoicesVoidCreate()` */
  static readonly SalesInvoicesVoidCreatePath = '/api/sales/invoices/{id}/void/';

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesVoidCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesInvoicesVoidCreate$Json$Response(params: SalesInvoicesVoidCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesVoidCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesVoidCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesInvoicesVoidCreate$Json(params: SalesInvoicesVoidCreate$Json$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesVoidCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesVoidCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesInvoicesVoidCreate$XWwwFormUrlencoded$Response(params: SalesInvoicesVoidCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesVoidCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesVoidCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesInvoicesVoidCreate$XWwwFormUrlencoded(params: SalesInvoicesVoidCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesVoidCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesInvoicesVoidCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesInvoicesVoidCreate$FormData$Response(params: SalesInvoicesVoidCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Invoice>> {
    const obs = salesInvoicesVoidCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * POST makes a held sale (no number, no stock). PATCH edits it while
   * held; DELETE cancels it. /complete/ finishes the sale; /void/ cancels a
   * completed one.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesInvoicesVoidCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesInvoicesVoidCreate$FormData(params: SalesInvoicesVoidCreate$FormData$Params, context?: HttpContext): Observable<Invoice> {
    const resp = this.salesInvoicesVoidCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Invoice>): Invoice => r.body)
    );
  }

  /** Path part for operation `salesPaymentsList()` */
  static readonly SalesPaymentsListPath = '/api/sales/payments/';

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesPaymentsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesPaymentsList$Response(params?: SalesPaymentsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedCustomerPaymentList>> {
    const obs = salesPaymentsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesPaymentsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesPaymentsList(params?: SalesPaymentsList$Params, context?: HttpContext): Observable<PaginatedCustomerPaymentList> {
    const resp = this.salesPaymentsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedCustomerPaymentList>): PaginatedCustomerPaymentList => r.body)
    );
  }

  /** Path part for operation `salesPaymentsCreate()` */
  static readonly SalesPaymentsCreatePath = '/api/sales/payments/';

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesPaymentsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesPaymentsCreate$Json$Response(params: SalesPaymentsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
    const obs = salesPaymentsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesPaymentsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesPaymentsCreate$Json(params: SalesPaymentsCreate$Json$Params, context?: HttpContext): Observable<CustomerPayment> {
    const resp = this.salesPaymentsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CustomerPayment>): CustomerPayment => r.body)
    );
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesPaymentsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesPaymentsCreate$XWwwFormUrlencoded$Response(params: SalesPaymentsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
    const obs = salesPaymentsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesPaymentsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesPaymentsCreate$XWwwFormUrlencoded(params: SalesPaymentsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<CustomerPayment> {
    const resp = this.salesPaymentsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CustomerPayment>): CustomerPayment => r.body)
    );
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesPaymentsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesPaymentsCreate$FormData$Response(params: SalesPaymentsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
    const obs = salesPaymentsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesPaymentsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesPaymentsCreate$FormData(params: SalesPaymentsCreate$FormData$Params, context?: HttpContext): Observable<CustomerPayment> {
    const resp = this.salesPaymentsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CustomerPayment>): CustomerPayment => r.body)
    );
  }

  /** Path part for operation `salesPaymentsRetrieve()` */
  static readonly SalesPaymentsRetrievePath = '/api/sales/payments/{id}/';

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesPaymentsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesPaymentsRetrieve$Response(params: SalesPaymentsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
    const obs = salesPaymentsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesPaymentsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesPaymentsRetrieve(params: SalesPaymentsRetrieve$Params, context?: HttpContext): Observable<CustomerPayment> {
    const resp = this.salesPaymentsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CustomerPayment>): CustomerPayment => r.body)
    );
  }

  /** Path part for operation `salesPaymentsVoidCreate()` */
  static readonly SalesPaymentsVoidCreatePath = '/api/sales/payments/{id}/void/';

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesPaymentsVoidCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesPaymentsVoidCreate$Json$Response(params: SalesPaymentsVoidCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
    const obs = salesPaymentsVoidCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesPaymentsVoidCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesPaymentsVoidCreate$Json(params: SalesPaymentsVoidCreate$Json$Params, context?: HttpContext): Observable<CustomerPayment> {
    const resp = this.salesPaymentsVoidCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CustomerPayment>): CustomerPayment => r.body)
    );
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesPaymentsVoidCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesPaymentsVoidCreate$XWwwFormUrlencoded$Response(params: SalesPaymentsVoidCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
    const obs = salesPaymentsVoidCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesPaymentsVoidCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesPaymentsVoidCreate$XWwwFormUrlencoded(params: SalesPaymentsVoidCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<CustomerPayment> {
    const resp = this.salesPaymentsVoidCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CustomerPayment>): CustomerPayment => r.body)
    );
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesPaymentsVoidCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesPaymentsVoidCreate$FormData$Response(params: SalesPaymentsVoidCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerPayment>> {
    const obs = salesPaymentsVoidCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * A payment is applied in full when it is saved, and frozen after.
   * Leave `allocations` out to apply it to the oldest invoices first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesPaymentsVoidCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesPaymentsVoidCreate$FormData(params: SalesPaymentsVoidCreate$FormData$Params, context?: HttpContext): Observable<CustomerPayment> {
    const resp = this.salesPaymentsVoidCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CustomerPayment>): CustomerPayment => r.body)
    );
  }

  /** Path part for operation `salesQuotationsList()` */
  static readonly SalesQuotationsListPath = '/api/sales/quotations/';

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsList$Response(params?: SalesQuotationsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedQuotationList>> {
    const obs = salesQuotationsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsList(params?: SalesQuotationsList$Params, context?: HttpContext): Observable<PaginatedQuotationList> {
    const resp = this.salesQuotationsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedQuotationList>): PaginatedQuotationList => r.body)
    );
  }

  /** Path part for operation `salesQuotationsCreate()` */
  static readonly SalesQuotationsCreatePath = '/api/sales/quotations/';

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesQuotationsCreate$Json$Response(params: SalesQuotationsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesQuotationsCreate$Json(params: SalesQuotationsCreate$Json$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesQuotationsCreate$XWwwFormUrlencoded$Response(params: SalesQuotationsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesQuotationsCreate$XWwwFormUrlencoded(params: SalesQuotationsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesQuotationsCreate$FormData$Response(params: SalesQuotationsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesQuotationsCreate$FormData(params: SalesQuotationsCreate$FormData$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /** Path part for operation `salesQuotationsRetrieve()` */
  static readonly SalesQuotationsRetrievePath = '/api/sales/quotations/{id}/';

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsRetrieve$Response(params: SalesQuotationsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsRetrieve(params: SalesQuotationsRetrieve$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /** Path part for operation `salesQuotationsDestroy()` */
  static readonly SalesQuotationsDestroyPath = '/api/sales/quotations/{id}/';

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsDestroy()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsDestroy$Response(params: SalesQuotationsDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = salesQuotationsDestroy(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsDestroy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsDestroy(params: SalesQuotationsDestroy$Params, context?: HttpContext): Observable<void> {
    const resp = this.salesQuotationsDestroy$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `salesQuotationsPartialUpdate()` */
  static readonly SalesQuotationsPartialUpdatePath = '/api/sales/quotations/{id}/';

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesQuotationsPartialUpdate$Json$Response(params: SalesQuotationsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesQuotationsPartialUpdate$Json(params: SalesQuotationsPartialUpdate$Json$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesQuotationsPartialUpdate$XWwwFormUrlencoded$Response(params: SalesQuotationsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesQuotationsPartialUpdate$XWwwFormUrlencoded(params: SalesQuotationsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesQuotationsPartialUpdate$FormData$Response(params: SalesQuotationsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesQuotationsPartialUpdate$FormData(params: SalesQuotationsPartialUpdate$FormData$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /** Path part for operation `salesQuotationsAcceptCreate()` */
  static readonly SalesQuotationsAcceptCreatePath = '/api/sales/quotations/{id}/accept/';

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsAcceptCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsAcceptCreate$Response(params: SalesQuotationsAcceptCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsAcceptCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsAcceptCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsAcceptCreate(params: SalesQuotationsAcceptCreate$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsAcceptCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /** Path part for operation `salesQuotationsRejectCreate()` */
  static readonly SalesQuotationsRejectCreatePath = '/api/sales/quotations/{id}/reject/';

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsRejectCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesQuotationsRejectCreate$Json$Response(params: SalesQuotationsRejectCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsRejectCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsRejectCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesQuotationsRejectCreate$Json(params: SalesQuotationsRejectCreate$Json$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsRejectCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsRejectCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesQuotationsRejectCreate$XWwwFormUrlencoded$Response(params: SalesQuotationsRejectCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsRejectCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsRejectCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesQuotationsRejectCreate$XWwwFormUrlencoded(params: SalesQuotationsRejectCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsRejectCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsRejectCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesQuotationsRejectCreate$FormData$Response(params: SalesQuotationsRejectCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsRejectCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsRejectCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesQuotationsRejectCreate$FormData(params: SalesQuotationsRejectCreate$FormData$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsRejectCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /** Path part for operation `salesQuotationsSendCreate()` */
  static readonly SalesQuotationsSendCreatePath = '/api/sales/quotations/{id}/send/';

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesQuotationsSendCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsSendCreate$Response(params: SalesQuotationsSendCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Quotation>> {
    const obs = salesQuotationsSendCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Draft and sent quotations are edited freely; send, accept and reject
   * are actions. Only a draft can be deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesQuotationsSendCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesQuotationsSendCreate(params: SalesQuotationsSendCreate$Params, context?: HttpContext): Observable<Quotation> {
    const resp = this.salesQuotationsSendCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Quotation>): Quotation => r.body)
    );
  }

  /** Path part for operation `salesReturnsList()` */
  static readonly SalesReturnsListPath = '/api/sales/returns/';

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesReturnsList$Response(params?: SalesReturnsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedSalesReturnList>> {
    const obs = salesReturnsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesReturnsList(params?: SalesReturnsList$Params, context?: HttpContext): Observable<PaginatedSalesReturnList> {
    const resp = this.salesReturnsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedSalesReturnList>): PaginatedSalesReturnList => r.body)
    );
  }

  /** Path part for operation `salesReturnsCreate()` */
  static readonly SalesReturnsCreatePath = '/api/sales/returns/';

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesReturnsCreate$Json$Response(params: SalesReturnsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
    const obs = salesReturnsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesReturnsCreate$Json(params: SalesReturnsCreate$Json$Params, context?: HttpContext): Observable<SalesReturn> {
    const resp = this.salesReturnsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SalesReturn>): SalesReturn => r.body)
    );
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesReturnsCreate$XWwwFormUrlencoded$Response(params: SalesReturnsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
    const obs = salesReturnsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesReturnsCreate$XWwwFormUrlencoded(params: SalesReturnsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<SalesReturn> {
    const resp = this.salesReturnsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SalesReturn>): SalesReturn => r.body)
    );
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesReturnsCreate$FormData$Response(params: SalesReturnsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
    const obs = salesReturnsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesReturnsCreate$FormData(params: SalesReturnsCreate$FormData$Params, context?: HttpContext): Observable<SalesReturn> {
    const resp = this.salesReturnsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SalesReturn>): SalesReturn => r.body)
    );
  }

  /** Path part for operation `salesReturnsRetrieve()` */
  static readonly SalesReturnsRetrievePath = '/api/sales/returns/{id}/';

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesReturnsRetrieve$Response(params: SalesReturnsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
    const obs = salesReturnsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesReturnsRetrieve(params: SalesReturnsRetrieve$Params, context?: HttpContext): Observable<SalesReturn> {
    const resp = this.salesReturnsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SalesReturn>): SalesReturn => r.body)
    );
  }

  /** Path part for operation `salesReturnsDestroy()` */
  static readonly SalesReturnsDestroyPath = '/api/sales/returns/{id}/';

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsDestroy()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesReturnsDestroy$Response(params: SalesReturnsDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = salesReturnsDestroy(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsDestroy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesReturnsDestroy(params: SalesReturnsDestroy$Params, context?: HttpContext): Observable<void> {
    const resp = this.salesReturnsDestroy$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `salesReturnsPartialUpdate()` */
  static readonly SalesReturnsPartialUpdatePath = '/api/sales/returns/{id}/';

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesReturnsPartialUpdate$Json$Response(params: SalesReturnsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
    const obs = salesReturnsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  salesReturnsPartialUpdate$Json(params: SalesReturnsPartialUpdate$Json$Params, context?: HttpContext): Observable<SalesReturn> {
    const resp = this.salesReturnsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SalesReturn>): SalesReturn => r.body)
    );
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesReturnsPartialUpdate$XWwwFormUrlencoded$Response(params: SalesReturnsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
    const obs = salesReturnsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  salesReturnsPartialUpdate$XWwwFormUrlencoded(params: SalesReturnsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<SalesReturn> {
    const resp = this.salesReturnsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SalesReturn>): SalesReturn => r.body)
    );
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesReturnsPartialUpdate$FormData$Response(params: SalesReturnsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
    const obs = salesReturnsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  salesReturnsPartialUpdate$FormData(params: SalesReturnsPartialUpdate$FormData$Params, context?: HttpContext): Observable<SalesReturn> {
    const resp = this.salesReturnsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SalesReturn>): SalesReturn => r.body)
    );
  }

  /** Path part for operation `salesReturnsPostCreate()` */
  static readonly SalesReturnsPostCreatePath = '/api/sales/returns/{id}/post/';

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salesReturnsPostCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesReturnsPostCreate$Response(params: SalesReturnsPostCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SalesReturn>> {
    const obs = salesReturnsPostCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stamps created_by and updated_by from the signed-in user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salesReturnsPostCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salesReturnsPostCreate(params: SalesReturnsPostCreate$Params, context?: HttpContext): Observable<SalesReturn> {
    const resp = this.salesReturnsPostCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SalesReturn>): SalesReturn => r.body)
    );
  }

}
