/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { InitialPassword } from '../models/initial-password';
import { PaginatedUserList } from '../models/paginated-user-list';
import { User } from '../models/user';
import { UserCreated } from '../models/user-created';
import { usersActivateCreate } from '../fn/users/users-activate-create';
import { UsersActivateCreate$Params } from '../fn/users/users-activate-create';
import { usersCreate$FormData } from '../fn/users/users-create-form-data';
import { UsersCreate$FormData$Params } from '../fn/users/users-create-form-data';
import { usersCreate$Json } from '../fn/users/users-create-json';
import { UsersCreate$Json$Params } from '../fn/users/users-create-json';
import { usersCreate$XWwwFormUrlencoded } from '../fn/users/users-create-x-www-form-urlencoded';
import { UsersCreate$XWwwFormUrlencoded$Params } from '../fn/users/users-create-x-www-form-urlencoded';
import { usersDeactivateCreate } from '../fn/users/users-deactivate-create';
import { UsersDeactivateCreate$Params } from '../fn/users/users-deactivate-create';
import { usersList } from '../fn/users/users-list';
import { UsersList$Params } from '../fn/users/users-list';
import { usersPartialUpdate$FormData } from '../fn/users/users-partial-update-form-data';
import { UsersPartialUpdate$FormData$Params } from '../fn/users/users-partial-update-form-data';
import { usersPartialUpdate$Json } from '../fn/users/users-partial-update-json';
import { UsersPartialUpdate$Json$Params } from '../fn/users/users-partial-update-json';
import { usersPartialUpdate$XWwwFormUrlencoded } from '../fn/users/users-partial-update-x-www-form-urlencoded';
import { UsersPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/users/users-partial-update-x-www-form-urlencoded';
import { usersResetPasswordCreate } from '../fn/users/users-reset-password-create';
import { UsersResetPasswordCreate$Params } from '../fn/users/users-reset-password-create';
import { usersRetrieve } from '../fn/users/users-retrieve';
import { UsersRetrieve$Params } from '../fn/users/users-retrieve';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `usersList()` */
  static readonly UsersListPath = '/api/users/';

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersList()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersList$Response(params?: UsersList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedUserList>> {
    const obs = usersList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersList(params?: UsersList$Params, context?: HttpContext): Observable<PaginatedUserList> {
    const resp = this.usersList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedUserList>): PaginatedUserList => r.body)
    );
  }

  /** Path part for operation `usersCreate()` */
  static readonly UsersCreatePath = '/api/users/';

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersCreate$Json$Response(params: UsersCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserCreated>> {
    const obs = usersCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersCreate$Json(params: UsersCreate$Json$Params, context?: HttpContext): Observable<UserCreated> {
    const resp = this.usersCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserCreated>): UserCreated => r.body)
    );
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  usersCreate$XWwwFormUrlencoded$Response(params: UsersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<UserCreated>> {
    const obs = usersCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  usersCreate$XWwwFormUrlencoded(params: UsersCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<UserCreated> {
    const resp = this.usersCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserCreated>): UserCreated => r.body)
    );
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  usersCreate$FormData$Response(params: UsersCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<UserCreated>> {
    const obs = usersCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  usersCreate$FormData(params: UsersCreate$FormData$Params, context?: HttpContext): Observable<UserCreated> {
    const resp = this.usersCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserCreated>): UserCreated => r.body)
    );
  }

  /** Path part for operation `usersRetrieve()` */
  static readonly UsersRetrievePath = '/api/users/{id}/';

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersRetrieve$Response(params: UsersRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    const obs = usersRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersRetrieve(params: UsersRetrieve$Params, context?: HttpContext): Observable<User> {
    const resp = this.usersRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

  /** Path part for operation `usersPartialUpdate()` */
  static readonly UsersPartialUpdatePath = '/api/users/{id}/';

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersPartialUpdate$Json$Response(params: UsersPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    const obs = usersPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersPartialUpdate$Json(params: UsersPartialUpdate$Json$Params, context?: HttpContext): Observable<User> {
    const resp = this.usersPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  usersPartialUpdate$XWwwFormUrlencoded$Response(params: UsersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    const obs = usersPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  usersPartialUpdate$XWwwFormUrlencoded(params: UsersPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<User> {
    const resp = this.usersPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  usersPartialUpdate$FormData$Response(params: UsersPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    const obs = usersPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  usersPartialUpdate$FormData(params: UsersPartialUpdate$FormData$Params, context?: HttpContext): Observable<User> {
    const resp = this.usersPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

  /** Path part for operation `usersActivateCreate()` */
  static readonly UsersActivateCreatePath = '/api/users/{id}/activate/';

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersActivateCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersActivateCreate$Response(params: UsersActivateCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    const obs = usersActivateCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersActivateCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersActivateCreate(params: UsersActivateCreate$Params, context?: HttpContext): Observable<User> {
    const resp = this.usersActivateCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

  /** Path part for operation `usersDeactivateCreate()` */
  static readonly UsersDeactivateCreatePath = '/api/users/{id}/deactivate/';

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersDeactivateCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersDeactivateCreate$Response(params: UsersDeactivateCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    const obs = usersDeactivateCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersDeactivateCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersDeactivateCreate(params: UsersDeactivateCreate$Params, context?: HttpContext): Observable<User> {
    const resp = this.usersDeactivateCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

  /** Path part for operation `usersResetPasswordCreate()` */
  static readonly UsersResetPasswordCreatePath = '/api/users/{id}/reset-password/';

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersResetPasswordCreate()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersResetPasswordCreate$Response(params: UsersResetPasswordCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<InitialPassword>> {
    const obs = usersResetPasswordCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Admin only. Users are deactivated, never deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersResetPasswordCreate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersResetPasswordCreate(params: UsersResetPasswordCreate$Params, context?: HttpContext): Observable<InitialPassword> {
    const resp = this.usersResetPasswordCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<InitialPassword>): InitialPassword => r.body)
    );
  }

}
