/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginatedWarrantyClaimList } from '../models/paginated-warranty-claim-list';
import { WarrantyClaim } from '../models/warranty-claim';
import { warrantyClaimsCreate$FormData } from '../fn/warranty/warranty-claims-create-form-data';
import { WarrantyClaimsCreate$FormData$Params } from '../fn/warranty/warranty-claims-create-form-data';
import { warrantyClaimsCreate$Json } from '../fn/warranty/warranty-claims-create-json';
import { WarrantyClaimsCreate$Json$Params } from '../fn/warranty/warranty-claims-create-json';
import { warrantyClaimsCreate$XWwwFormUrlencoded } from '../fn/warranty/warranty-claims-create-x-www-form-urlencoded';
import { WarrantyClaimsCreate$XWwwFormUrlencoded$Params } from '../fn/warranty/warranty-claims-create-x-www-form-urlencoded';
import { warrantyClaimsDestroy } from '../fn/warranty/warranty-claims-destroy';
import { WarrantyClaimsDestroy$Params } from '../fn/warranty/warranty-claims-destroy';
import { warrantyClaimsList } from '../fn/warranty/warranty-claims-list';
import { WarrantyClaimsList$Params } from '../fn/warranty/warranty-claims-list';
import { warrantyClaimsPartialUpdate$FormData } from '../fn/warranty/warranty-claims-partial-update-form-data';
import { WarrantyClaimsPartialUpdate$FormData$Params } from '../fn/warranty/warranty-claims-partial-update-form-data';
import { warrantyClaimsPartialUpdate$Json } from '../fn/warranty/warranty-claims-partial-update-json';
import { WarrantyClaimsPartialUpdate$Json$Params } from '../fn/warranty/warranty-claims-partial-update-json';
import { warrantyClaimsPartialUpdate$XWwwFormUrlencoded } from '../fn/warranty/warranty-claims-partial-update-x-www-form-urlencoded';
import { WarrantyClaimsPartialUpdate$XWwwFormUrlencoded$Params } from '../fn/warranty/warranty-claims-partial-update-x-www-form-urlencoded';
import { warrantyClaimsRetrieve } from '../fn/warranty/warranty-claims-retrieve';
import { WarrantyClaimsRetrieve$Params } from '../fn/warranty/warranty-claims-retrieve';

@Injectable({ providedIn: 'root' })
export class WarrantyService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `warrantyClaimsList()` */
  static readonly WarrantyClaimsListPath = '/api/warranty/claims/';

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsList()` instead.
   *
   * This method doesn't expect any request body.
   */
  warrantyClaimsList$Response(params?: WarrantyClaimsList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedWarrantyClaimList>> {
    const obs = warrantyClaimsList(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  warrantyClaimsList(params?: WarrantyClaimsList$Params, context?: HttpContext): Observable<PaginatedWarrantyClaimList> {
    const resp = this.warrantyClaimsList$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PaginatedWarrantyClaimList>): PaginatedWarrantyClaimList => r.body)
    );
  }

  /** Path part for operation `warrantyClaimsCreate()` */
  static readonly WarrantyClaimsCreatePath = '/api/warranty/claims/';

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsCreate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  warrantyClaimsCreate$Json$Response(params: WarrantyClaimsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<WarrantyClaim>> {
    const obs = warrantyClaimsCreate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsCreate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  warrantyClaimsCreate$Json(params: WarrantyClaimsCreate$Json$Params, context?: HttpContext): Observable<WarrantyClaim> {
    const resp = this.warrantyClaimsCreate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<WarrantyClaim>): WarrantyClaim => r.body)
    );
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsCreate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  warrantyClaimsCreate$XWwwFormUrlencoded$Response(params: WarrantyClaimsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<WarrantyClaim>> {
    const obs = warrantyClaimsCreate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsCreate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  warrantyClaimsCreate$XWwwFormUrlencoded(params: WarrantyClaimsCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<WarrantyClaim> {
    const resp = this.warrantyClaimsCreate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<WarrantyClaim>): WarrantyClaim => r.body)
    );
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsCreate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  warrantyClaimsCreate$FormData$Response(params: WarrantyClaimsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<WarrantyClaim>> {
    const obs = warrantyClaimsCreate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsCreate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  warrantyClaimsCreate$FormData(params: WarrantyClaimsCreate$FormData$Params, context?: HttpContext): Observable<WarrantyClaim> {
    const resp = this.warrantyClaimsCreate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<WarrantyClaim>): WarrantyClaim => r.body)
    );
  }

  /** Path part for operation `warrantyClaimsRetrieve()` */
  static readonly WarrantyClaimsRetrievePath = '/api/warranty/claims/{id}/';

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  warrantyClaimsRetrieve$Response(params: WarrantyClaimsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<WarrantyClaim>> {
    const obs = warrantyClaimsRetrieve(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  warrantyClaimsRetrieve(params: WarrantyClaimsRetrieve$Params, context?: HttpContext): Observable<WarrantyClaim> {
    const resp = this.warrantyClaimsRetrieve$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<WarrantyClaim>): WarrantyClaim => r.body)
    );
  }

  /** Path part for operation `warrantyClaimsDestroy()` */
  static readonly WarrantyClaimsDestroyPath = '/api/warranty/claims/{id}/';

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsDestroy()` instead.
   *
   * This method doesn't expect any request body.
   */
  warrantyClaimsDestroy$Response(params: WarrantyClaimsDestroy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = warrantyClaimsDestroy(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsDestroy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  warrantyClaimsDestroy(params: WarrantyClaimsDestroy$Params, context?: HttpContext): Observable<void> {
    const resp = this.warrantyClaimsDestroy$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `warrantyClaimsPartialUpdate()` */
  static readonly WarrantyClaimsPartialUpdatePath = '/api/warranty/claims/{id}/';

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsPartialUpdate$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  warrantyClaimsPartialUpdate$Json$Response(params: WarrantyClaimsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<WarrantyClaim>> {
    const obs = warrantyClaimsPartialUpdate$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsPartialUpdate$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  warrantyClaimsPartialUpdate$Json(params: WarrantyClaimsPartialUpdate$Json$Params, context?: HttpContext): Observable<WarrantyClaim> {
    const resp = this.warrantyClaimsPartialUpdate$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<WarrantyClaim>): WarrantyClaim => r.body)
    );
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsPartialUpdate$XWwwFormUrlencoded()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  warrantyClaimsPartialUpdate$XWwwFormUrlencoded$Response(params: WarrantyClaimsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<WarrantyClaim>> {
    const obs = warrantyClaimsPartialUpdate$XWwwFormUrlencoded(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsPartialUpdate$XWwwFormUrlencoded$Response()` instead.
   *
   * This method sends `application/x-www-form-urlencoded` and handles request body of type `application/x-www-form-urlencoded`.
   */
  warrantyClaimsPartialUpdate$XWwwFormUrlencoded(params: WarrantyClaimsPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<WarrantyClaim> {
    const resp = this.warrantyClaimsPartialUpdate$XWwwFormUrlencoded$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<WarrantyClaim>): WarrantyClaim => r.body)
    );
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warrantyClaimsPartialUpdate$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  warrantyClaimsPartialUpdate$FormData$Response(params: WarrantyClaimsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<WarrantyClaim>> {
    const obs = warrantyClaimsPartialUpdate$FormData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Newest first. Any status may follow any other.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warrantyClaimsPartialUpdate$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  warrantyClaimsPartialUpdate$FormData(params: WarrantyClaimsPartialUpdate$FormData$Params, context?: HttpContext): Observable<WarrantyClaim> {
    const resp = this.warrantyClaimsPartialUpdate$FormData$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<WarrantyClaim>): WarrantyClaim => r.body)
    );
  }

}
