/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CurrentRate } from '../../models/current-rate';

export interface CompanyRateRetrieve$Params {
}

export function companyRateRetrieve(http: HttpClient, rootUrl: string, params?: CompanyRateRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentRate>> {
  const rb = new RequestBuilder(rootUrl, companyRateRetrieve.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CurrentRate>;
    })
  );
}

companyRateRetrieve.PATH = '/api/company/rate/';
