/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentCounter } from '../../models/document-counter';

export interface CompanyNumberingRetrieve$Params {

/**
 * A unique integer value identifying this document counter.
 */
  id: number;
}

export function companyNumberingRetrieve(http: HttpClient, rootUrl: string, params: CompanyNumberingRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentCounter>> {
  const rb = new RequestBuilder(rootUrl, companyNumberingRetrieve.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentCounter>;
    })
  );
}

companyNumberingRetrieve.PATH = '/api/company/numbering/{id}/';
