/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentCounter } from '../../models/document-counter';
import { PatchedDocumentCounterRequest } from '../../models/patched-document-counter-request';

export interface CompanyNumberingPartialUpdate$FormData$Params {

/**
 * A unique integer value identifying this document counter.
 */
  id: number;
      body?: PatchedDocumentCounterRequest
}

export function companyNumberingPartialUpdate$FormData(http: HttpClient, rootUrl: string, params: CompanyNumberingPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentCounter>> {
  const rb = new RequestBuilder(rootUrl, companyNumberingPartialUpdate$FormData.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentCounter>;
    })
  );
}

companyNumberingPartialUpdate$FormData.PATH = '/api/company/numbering/{id}/';
