/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExchangeRate } from '../../models/exchange-rate';

export interface CompanyExchangeRatesRetrieve$Params {

/**
 * A unique integer value identifying this exchange rate.
 */
  id: number;
}

export function companyExchangeRatesRetrieve(http: HttpClient, rootUrl: string, params: CompanyExchangeRatesRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<ExchangeRate>> {
  const rb = new RequestBuilder(rootUrl, companyExchangeRatesRetrieve.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExchangeRate>;
    })
  );
}

companyExchangeRatesRetrieve.PATH = '/api/company/exchange-rates/{id}/';
