/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentNote } from '../../models/payment-note';
import { PaymentNoteRequest } from '../../models/payment-note-request';

export interface CompanyPaymentNotesCreate$XWwwFormUrlencoded$Params {
      body: PaymentNoteRequest
}

export function companyPaymentNotesCreate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: CompanyPaymentNotesCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentNote>> {
  const rb = new RequestBuilder(rootUrl, companyPaymentNotesCreate$XWwwFormUrlencoded.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentNote>;
    })
  );
}

companyPaymentNotesCreate$XWwwFormUrlencoded.PATH = '/api/company/payment-notes/';
