/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyProfile } from '../../models/company-profile';
import { PatchedCompanyProfileRequest } from '../../models/patched-company-profile-request';

export interface CompanyProfilePartialUpdate$Json$Params {
      body?: PatchedCompanyProfileRequest
}

export function companyProfilePartialUpdate$Json(http: HttpClient, rootUrl: string, params?: CompanyProfilePartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyProfile>> {
  const rb = new RequestBuilder(rootUrl, companyProfilePartialUpdate$Json.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyProfile>;
    })
  );
}

companyProfilePartialUpdate$Json.PATH = '/api/company/profile/';
