/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedPaymentNoteRequest } from '../../models/patched-payment-note-request';
import { PaymentNote } from '../../models/payment-note';

export interface CompanyPaymentNotesPartialUpdate$Json$Params {

/**
 * A unique integer value identifying this payment note.
 */
  id: number;
      body?: PatchedPaymentNoteRequest
}

export function companyPaymentNotesPartialUpdate$Json(http: HttpClient, rootUrl: string, params: CompanyPaymentNotesPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentNote>> {
  const rb = new RequestBuilder(rootUrl, companyPaymentNotesPartialUpdate$Json.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentNote>;
    })
  );
}

companyPaymentNotesPartialUpdate$Json.PATH = '/api/company/payment-notes/{id}/';
