/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExchangeRate } from '../../models/exchange-rate';
import { PatchedExchangeRateRequest } from '../../models/patched-exchange-rate-request';

export interface CompanyExchangeRatesPartialUpdate$XWwwFormUrlencoded$Params {

/**
 * A unique integer value identifying this exchange rate.
 */
  id: number;
      body?: PatchedExchangeRateRequest
}

export function companyExchangeRatesPartialUpdate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: CompanyExchangeRatesPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<ExchangeRate>> {
  const rb = new RequestBuilder(rootUrl, companyExchangeRatesPartialUpdate$XWwwFormUrlencoded.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExchangeRate>;
    })
  );
}

companyExchangeRatesPartialUpdate$XWwwFormUrlencoded.PATH = '/api/company/exchange-rates/{id}/';
