/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedPaymentNoteList } from '../../models/paginated-payment-note-list';

export interface CompanyPaymentNotesList$Params {

/**
 * true: active only; false: inactive only.
 */
  active?: 'false' | 'true';

/**
 * A page number within the paginated result set.
 */
  page?: number;
}

export function companyPaymentNotesList(http: HttpClient, rootUrl: string, params?: CompanyPaymentNotesList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedPaymentNoteList>> {
  const rb = new RequestBuilder(rootUrl, companyPaymentNotesList.PATH, 'get');
  if (params) {
    rb.query('active', params.active, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedPaymentNoteList>;
    })
  );
}

companyPaymentNotesList.PATH = '/api/company/payment-notes/';
