/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedExchangeRateList } from '../../models/paginated-exchange-rate-list';

export interface CompanyExchangeRatesList$Params {

/**
 * A page number within the paginated result set.
 */
  page?: number;
}

export function companyExchangeRatesList(http: HttpClient, rootUrl: string, params?: CompanyExchangeRatesList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedExchangeRateList>> {
  const rb = new RequestBuilder(rootUrl, companyExchangeRatesList.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedExchangeRateList>;
    })
  );
}

companyExchangeRatesList.PATH = '/api/company/exchange-rates/';
