/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentNote } from '../../models/payment-note';
import { PaymentNoteRequest } from '../../models/payment-note-request';

export interface CompanyPaymentNotesUpdate$FormData$Params {

/**
 * A unique integer value identifying this payment note.
 */
  id: number;
      body: PaymentNoteRequest
}

export function companyPaymentNotesUpdate$FormData(http: HttpClient, rootUrl: string, params: CompanyPaymentNotesUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentNote>> {
  const rb = new RequestBuilder(rootUrl, companyPaymentNotesUpdate$FormData.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentNote>;
    })
  );
}

companyPaymentNotesUpdate$FormData.PATH = '/api/company/payment-notes/{id}/';
