/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Detail } from '../../models/detail';
import { PasswordChangeRequest } from '../../models/password-change-request';

export interface AuthPasswordCreate$FormData$Params {
      body: PasswordChangeRequest
}

export function authPasswordCreate$FormData(http: HttpClient, rootUrl: string, params: AuthPasswordCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Detail>> {
  const rb = new RequestBuilder(rootUrl, authPasswordCreate$FormData.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Detail>;
    })
  );
}

authPasswordCreate$FormData.PATH = '/api/auth/password/';
