/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Detail } from '../../models/detail';
import { PasswordChangeRequest } from '../../models/password-change-request';

export interface AuthPasswordCreate$XWwwFormUrlencoded$Params {
      body: PasswordChangeRequest
}

export function authPasswordCreate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: AuthPasswordCreate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Detail>> {
  const rb = new RequestBuilder(rootUrl, authPasswordCreate$XWwwFormUrlencoded.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Detail>;
    })
  );
}

authPasswordCreate$XWwwFormUrlencoded.PATH = '/api/auth/password/';
