/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Unit } from '../../models/unit';
import { UnitRequest } from '../../models/unit-request';

export interface CatalogueUnitsCreate$FormData$Params {
      body: UnitRequest
}

export function catalogueUnitsCreate$FormData(http: HttpClient, rootUrl: string, params: CatalogueUnitsCreate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
  const rb = new RequestBuilder(rootUrl, catalogueUnitsCreate$FormData.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Unit>;
    })
  );
}

catalogueUnitsCreate$FormData.PATH = '/api/catalogue/units/';
