/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedCategoryList } from '../../models/paginated-category-list';

export interface CatalogueCategoriesList$Params {

/**
 * true: active only; false: inactive only.
 */
  active?: 'false' | 'true';

/**
 * A page number within the paginated result set.
 */
  page?: number;

/**
 * Parent category id.
 */
  parent?: number;

/**
 * Top-level categories only.
 */
  top_level?: 'false' | 'true';
}

export function catalogueCategoriesList(http: HttpClient, rootUrl: string, params?: CatalogueCategoriesList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedCategoryList>> {
  const rb = new RequestBuilder(rootUrl, catalogueCategoriesList.PATH, 'get');
  if (params) {
    rb.query('active', params.active, {});
    rb.query('page', params.page, {});
    rb.query('parent', params.parent, {});
    rb.query('top_level', params.top_level, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedCategoryList>;
    })
  );
}

catalogueCategoriesList.PATH = '/api/catalogue/categories/';
