/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Category } from '../../models/category';
import { PatchedCategoryRequest } from '../../models/patched-category-request';

export interface CatalogueCategoriesPartialUpdate$XWwwFormUrlencoded$Params {

/**
 * A unique integer value identifying this category.
 */
  id: number;
      body?: PatchedCategoryRequest
}

export function catalogueCategoriesPartialUpdate$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: CatalogueCategoriesPartialUpdate$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
  const rb = new RequestBuilder(rootUrl, catalogueCategoriesPartialUpdate$XWwwFormUrlencoded.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Category>;
    })
  );
}

catalogueCategoriesPartialUpdate$XWwwFormUrlencoded.PATH = '/api/catalogue/categories/{id}/';
