/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedProductRequest } from '../../models/patched-product-request';
import { Product } from '../../models/product';

export interface CatalogueProductsPartialUpdate$Json$Params {

/**
 * A unique integer value identifying this product.
 */
  id: number;
      body?: PatchedProductRequest
}

export function catalogueProductsPartialUpdate$Json(http: HttpClient, rootUrl: string, params: CatalogueProductsPartialUpdate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
  const rb = new RequestBuilder(rootUrl, catalogueProductsPartialUpdate$Json.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Product>;
    })
  );
}

catalogueProductsPartialUpdate$Json.PATH = '/api/catalogue/products/{id}/';
