/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductLookup } from '../../models/product-lookup';

export interface CatalogueProductsLookupList$Params {

/**
 * true: active only; false: inactive only.
 */
  active?: 'false' | 'true';

/**
 * At or below the reorder level.
 */
  below_reorder?: 'false' | 'true';

/**
 * Brand id.
 */
  brand?: number;

/**
 * Category id; a top-level one includes its sub-categories.
 */
  category?: number;

/**
 * Nothing on hand.
 */
  out_of_stock?: 'false' | 'true';

/**
 * Matches codes, names and numbers.
 */
  search?: string;
}

export function catalogueProductsLookupList(http: HttpClient, rootUrl: string, params?: CatalogueProductsLookupList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductLookup>>> {
  const rb = new RequestBuilder(rootUrl, catalogueProductsLookupList.PATH, 'get');
  if (params) {
    rb.query('active', params.active, {});
    rb.query('below_reorder', params.below_reorder, {});
    rb.query('brand', params.brand, {});
    rb.query('category', params.category, {});
    rb.query('out_of_stock', params.out_of_stock, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductLookup>>;
    })
  );
}

catalogueProductsLookupList.PATH = '/api/catalogue/products/lookup/';
