/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchedUnitRequest } from '../../models/patched-unit-request';
import { Unit } from '../../models/unit';

export interface CatalogueUnitsPartialUpdate$FormData$Params {

/**
 * A unique integer value identifying this unit.
 */
  id: number;
      body?: PatchedUnitRequest
}

export function catalogueUnitsPartialUpdate$FormData(http: HttpClient, rootUrl: string, params: CatalogueUnitsPartialUpdate$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<Unit>> {
  const rb = new RequestBuilder(rootUrl, catalogueUnitsPartialUpdate$FormData.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Unit>;
    })
  );
}

catalogueUnitsPartialUpdate$FormData.PATH = '/api/catalogue/units/{id}/';
